// GENERATED by scripts/bundle-probe.mjs from supabase/functions/aspire-probe. Do not edit by hand.
// Paste this whole file into the Supabase dashboard editor as the function "aspire-probe".

// ======================= client.ts =======================
// The only door to Aspire. Shared by every probe pass.
//
// Rules this file enforces:
// - Every data request is a GET. The only POST is the auth handshake, to a fixed list
//   of token paths. Anything else throws before it leaves the building.
// - A hard cap on total calls, spacing between calls, a time budget, and backoff on 429.
// - No secret or token ever lands in anything this returns.

export const BASE = 'https://cloud-api.youraspire.com';

// the handshake candidates, tried in this order. OAuth client credentials first.
export const AUTH_ATTEMPTS = [
  { name: 'OAuth2 client_credentials (form body)', path: '/connect/token', kind: 'oauth' },
  { name: 'OAuth2 client_credentials (form body)', path: '/oauth/token', kind: 'oauth' },
  { name: 'OAuth2 client_credentials (form body)', path: '/token', kind: 'oauth' },
  { name: 'Aspire JSON handshake { ClientId, Secret }', path: '/Authorization', kind: 'aspire' },
];
const AUTH_PATHS = AUTH_ATTEMPTS.map((a) => a.path);

type Fetch = (url: string, init?: any) => Promise<any>;
export interface ProbeOptions {
  clientId: string;
  secret: string;
  base?: string;
  fetch?: Fetch;
  sleep?: (ms: number) => Promise<void>;
  now?: Date;
  maxCalls?: number;
  spacingMs?: number;
  deadlineMs?: number; // stop and report before the host kills the function
  clock?: () => number;
}

const DATE_RE = /^\d{4}-\d{2}-\d{2}([T ]\d{2}:\d{2}(:\d{2}(\.\d+)?)?(Z|[+-]\d{2}:?\d{2})?)?$/;
export const isDate = (v: unknown) => typeof v === 'string' && DATE_RE.test(v);
export const typeOf = (v: unknown) => (v === null || v === undefined ? 'null' : Array.isArray(v) ? 'array' : isDate(v) ? 'date' : typeof v);

export function records(json: any): any[] | null {
  if (Array.isArray(json)) return json;
  if (json && Array.isArray(json.value)) return json.value;
  if (json && Array.isArray(json.Items)) return json.Items;
  if (json && Array.isArray(json.items)) return json.items;
  return null;
}
export function envelope(json: any): string {
  if (Array.isArray(json)) return 'bare JSON array';
  if (json && Array.isArray(json.value)) return 'OData { value: [...] }';
  if (json && Array.isArray(json.Items)) return '{ Items: [...] }';
  if (json && Array.isArray(json.items)) return '{ items: [...] }';
  return 'unrecognized';
}
export function fieldsOf(rec: any) {
  if (!rec || typeof rec !== 'object') return [];
  return Object.keys(rec).map((k) => ({ name: k, type: typeOf(rec[k]) }));
}
export const qs = (o: Record<string, string>) => Object.entries(o).map(([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(v)}`).join('&');

export async function openAspire(opts: ProbeOptions) {
  const base = (opts.base || BASE).replace(/\/+$/, '');
  const f: Fetch = opts.fetch || ((u, i) => fetch(u, i));
  const sleep = opts.sleep || ((ms: number) => new Promise((r) => setTimeout(r, ms)));
  const now = opts.now || new Date();
  const maxCalls = opts.maxCalls ?? 70;
  const spacing = opts.spacingMs ?? 350;
  const deadline = opts.deadlineMs ?? 110_000; // edge functions are cut off at about 150s on the free plan
  const clock = opts.clock || (() => Date.now());
  const started = clock();
  const elapsed = () => clock() - started;
  const s = { calls: 0, throttled: 0, outOfTime: false };
  const log: any[] = [];

  async function call(method: string, path: string, init: { headers?: any; body?: string } = {}) {
    const bare = path.split('?')[0];
    if (method !== 'GET' && !(method === 'POST' && AUTH_PATHS.includes(bare))) {
      throw new Error(`refused: ${method} ${bare}. The probe only reads.`);
    }
    for (let attempt = 0; attempt < 4; attempt++) {
      if (s.calls >= maxCalls || elapsed() > deadline) {
        const why = s.calls >= maxCalls ? 'call budget reached' : 'time budget reached';
        if (why === 'time budget reached') s.outOfTime = true;
        log.push({ method, path, skipped: why });
        return { status: 0, skipped: true, json: null, text: '', headers: {} as any };
      }
      s.calls++;
      if (s.calls > 1) await sleep(spacing);
      const t0 = Date.now();
      let res: any;
      try {
        res = await f(base + path, { method, headers: init.headers, body: init.body, signal: AbortSignal.timeout(20_000) });
      } catch (e) {
        log.push({ method, path, error: String((e as any)?.message || e) });
        return { status: -1, json: null, text: String(e), headers: {} as any };
      }
      const ms = Date.now() - t0;
      if (res.status === 429) {
        s.throttled++;
        const ra = Number(res.headers?.get?.('retry-after'));
        const wait = Number.isFinite(ra) && ra > 0 ? Math.min(ra, 60) * 1000 : 2000 * 2 ** attempt;
        if (elapsed() + wait > deadline) {
          s.outOfTime = true;
          log.push({ method, path, status: 429, ms, gave_up: 'waiting would run past the time budget' });
          return { status: 429, json: null, text: '', headers: {} as any };
        }
        log.push({ method, path, status: 429, ms, retry_in_ms: wait });
        await sleep(wait);
        continue;
      }
      const text = await res.text();
      let json: any = null;
      try { json = JSON.parse(text); } catch { /* not json */ }
      log.push({ method, path, status: res.status, ms });
      return { status: res.status, json, text, headers: res.headers };
    }
    log.push({ method, path, gave_up: 'still 429 after 4 tries' });
    return { status: 429, json: null, text: '', headers: {} as any };
  }

  // ---------- auth ----------
  const auth: any = { worked: null, attempts: [] };
  let authHeader: string | null = null;
  for (const a of AUTH_ATTEMPTS) {
    const body = a.kind === 'oauth'
      ? qs({ grant_type: 'client_credentials', client_id: opts.clientId, client_secret: opts.secret })
      : JSON.stringify({ ClientId: opts.clientId, Secret: opts.secret });
    const headers = a.kind === 'oauth'
      ? { 'Content-Type': 'application/x-www-form-urlencoded', Accept: 'application/json' }
      : { 'Content-Type': 'application/json', Accept: 'application/json' };
    const r = await call('POST', a.path, { headers, body });
    const keys = r.json && typeof r.json === 'object' ? Object.keys(r.json) : [];
    const tokenKey = ['access_token', 'Token', 'token', 'AccessToken', 'accessToken'].find((k) => typeof r.json?.[k] === 'string');
    const attempt: any = { name: a.name, request: `POST ${a.path} (${headers['Content-Type']})`, status: r.status, response_fields: keys };
    auth.attempts.push(attempt);
    if (!(r.status >= 200 && r.status < 300) || !tokenKey) continue;

    const token = r.json[tokenKey];
    const scheme = typeof r.json.token_type === 'string' ? r.json.token_type : 'Bearer';
    // prove it: one cheap GET, first as "<scheme> <token>", then the raw token
    for (const h of [`${scheme} ${token}`, token]) {
      const v = await call('GET', `/Divisions?${qs({ $top: '1' })}`, { headers: { Authorization: h, Accept: 'application/json' } });
      if (v.status >= 200 && v.status < 300) { authHeader = h; attempt.verified_with = h === token ? 'Authorization: <raw token>' : `Authorization: ${scheme} <token>`; break; }
      attempt[`verify_${h === token ? 'raw' : 'scheme'}_status`] = v.status;
    }
    if (!authHeader) continue;
    const exp = r.json.expires_in ?? r.json.ExpiresIn ?? r.json.expiration ?? r.json.Expiration ?? null;
    auth.worked = {
      endpoint: `POST ${base}${a.path}`,
      body: a.kind === 'oauth' ? 'form: grant_type=client_credentials, client_id, client_secret' : 'JSON: { "ClientId": "...", "Secret": "..." }',
      token_field: tokenKey,
      header: attempt.verified_with,
      token_shape: token.split('.').length === 3 ? 'JWT (three dot-separated parts)' : `opaque string, ${token.length} chars`,
      expires: exp,
      refresh_token_returned: ['refresh_token', 'RefreshToken', 'refreshToken'].some((k) => typeof r.json[k] === 'string'),
    };
    break;
  }

  const H = { Authorization: authHeader || '', Accept: 'application/json' };
  const get = (p: string) => call('GET', p, { headers: H });
  const footer = () => ({
    generated_at: now.toISOString(), base, calls_used: s.calls, call_budget: maxCalls, throttled: s.throttled,
    seconds: Math.round(elapsed() / 1000), stopped_early: s.outOfTime,
    // enforced by call(): anything but GET, or POST to a token path, throws before it is sent
    data_writes: 0,
  });
  const tail = (summary: string[]) => {
    if (s.throttled) summary.push(`Throttled ${s.throttled} time(s). Backed off and retried.`);
    if (s.outOfTime) summary.push('Stopped early to stay inside the time budget. Everything above is real; anything missing was skipped, not failed. Run it again to fill the gaps.');
    if (log.some((l) => l.skipped === 'call budget reached')) summary.push(`Hit the ${maxCalls}-call budget. Anything after that point was skipped, not failed.`);
  };
  return { base, now, get, auth, authed: !!authHeader, log, footer, tail };
}

// ======================= probe.ts =======================
// Aspire discovery probe, pass 1: the core resources. Reads only.
// Reports the shape of the data, never copies it. Sample records are reported as
// field names and types, not values. Only the rep, branch and division fields
// show example values, because that is the question being asked.
// The network door, login, budgets and 429 handling live in client.ts.


export const RESOURCES = [
  { name: 'Opportunities', paths: ['/Opportunities'] },
  { name: 'Properties', paths: ['/Properties'] },
  { name: 'Contracts', paths: ['/Contracts', '/ContractYears', '/Agreements'] },
  { name: 'Contacts', paths: ['/Contacts'] },
  { name: 'Invoices', paths: ['/Invoices'] },
  { name: 'Divisions', paths: ['/Divisions'] },
  // not asked for, but they answer question 4 and question 3
  { name: 'Branches', paths: ['/Branches'], extra: true },
  { name: 'OpportunityStatuses', paths: ['/OpportunityStatuses'], extra: true },
];

export async function probe(opts: ProbeOptions) {
  const c = await openAspire(opts);
  const { now, auth, get, log } = c;
  const notes: string[] = [];
  const resources: any = {};
  const samples: Record<string, any> = {};
  const open: any = { answer: 'unknown' };
  const ids: any = { rep: [], branch: [], division: [] };
  if (!c.authed) {
    notes.push('No auth handshake worked. Nothing past this point ran. Check the attempts list for the status each path returned.');
    return finish();
  }

  // ---------- 2. each resource ----------
  for (const res of RESOURCES) {
    const out: any = { exists: false, path: null, tried: [] };
    resources[res.name] = out;
    let sample: any = null;
    for (const p of res.paths) {
      const r = await get(`${p}?${qs({ $top: '1' })}`);
      out.tried.push({ path: p, status: r.status });
      if (r.status === 401 || r.status === 403) { out.exists = 'probably, but this credential is not allowed to read it'; out.path = p; break; }
      if (r.status >= 200 && r.status < 300) {
        const recs = records(r.json);
        out.exists = true; out.path = p; out.envelope = envelope(r.json);
        if (recs === null) { out.note = 'responded, but not with a list of records'; break; }
        sample = recs[0] || null;
        out.honours_top = recs.length <= 1;
        out.fields = fieldsOf(sample);
        break;
      }
    }
    if (out.exists !== true || !out.path) continue;
    samples[res.name] = sample;

    // record count: OData $count, then /$count, else unknown
    const c = await get(`${out.path}?${qs({ $top: '0', $count: 'true' })}`);
    const odataCount = c.json && (c.json['@odata.count'] ?? c.json['odata.count'] ?? c.json.Count ?? c.json.count);
    if (c.status === 200 && Number.isFinite(Number(odataCount))) { out.count = Number(odataCount); out.count_method = '$count=true'; }
    else {
      const c2 = await get(`${out.path}/$count`);
      const n = Number(String(c2.text || '').trim());
      if (c2.status === 200 && Number.isFinite(n) && String(c2.text).trim() !== '') { out.count = n; out.count_method = '/$count'; }
      else { out.count = null; out.count_method = 'none worked. Counting would mean paging the whole set, which this probe will not do.'; }
    }

    // modified-since: find a modified-looking date field, then prove the filter is applied, not ignored
    const mf = out.fields?.find((x: any) => /modif|updat|changed|lastedit|edited/i.test(x.name) && (x.type === 'date' || x.type === 'null'));
    if (!sample) out.modified_since = { supported: 'unknown', why: 'no records to inspect' };
    else if (!mf) out.modified_since = { supported: 'unknown', why: 'no field on the sample record looks like a modified date', candidates: out.fields.filter((x: any) => x.type === 'date').map((x: any) => x.name) };
    else {
      const future = '2100-01-01T00:00:00Z';
      const since = new Date(now.getTime() - 30 * 86400000).toISOString().replace(/\.\d{3}Z$/, 'Z');
      const a = await get(`${out.path}?${qs({ $filter: `${mf.name} ge ${future}`, $top: '1' })}`);
      const ar = records(a.json);
      if (a.status !== 200 || ar === null) out.modified_since = { field: mf.name, supported: false, why: `$filter on ${mf.name} returned ${a.status}` };
      else if (ar.length > 0) out.modified_since = { field: mf.name, supported: false, why: `the filter was accepted but ignored: a year-2100 cutoff still returned records` };
      else {
        const b = await get(`${out.path}?${qs({ $filter: `${mf.name} ge ${since}`, $top: '0', $count: 'true' })}`);
        const n = b.json && Number(b.json['@odata.count']);
        out.modified_since = { field: mf.name, supported: true, syntax: `$filter=${mf.name} ge ${since}`, changed_last_30_days: Number.isFinite(n) ? n : 'not counted' };
      }
    }
  }

  // ---------- 3. open opportunities, or only sold work? ----------
  const opp = resources.Opportunities;
  if (opp?.exists === true && samples.Opportunities) {
    const keys = Object.keys(samples.Opportunities);
    const pickKey = (re: RegExp) => keys.find((k) => re.test(k)) || null;
    const statusKey = pickKey(/^(opportunity)?status(name)?$/i) || pickKey(/status.*name/i) || pickKey(/status/i);
    const wonKey = pickKey(/won.?date/i);
    const lostKey = pickKey(/lost.?date/i);
    const stageKey = pickKey(/stage/i);
    const typeKey = pickKey(/^(opportunity)?type(name)?$/i);
    open.fields = { status: statusKey, won_date: wonKey, lost_date: lostKey, stage: stageKey, type: typeKey };

    const sel = [statusKey, stageKey, typeKey, wonKey, lostKey, opp.modified_since?.field].filter(Boolean).join(',');
    const order = opp.modified_since?.field ? { $orderby: `${opp.modified_since.field} desc` } : {};
    let r = await get(`/Opportunities?${qs({ $top: '500', ...(sel ? { $select: sel } : {}), ...order })}`);
    if (r.status !== 200 || !records(r.json)) r = await get(`/Opportunities?${qs({ $top: '200' })}`);
    const recs = records(r.json) || [];
    const tally = (k: string | null) => { const t: Record<string, number> = {}; if (!k) return t; for (const x of recs) { const v = x[k] === null || x[k] === undefined ? '(blank)' : String(x[k]); t[v] = (t[v] || 0) + 1; } return t; };
    open.sampled = recs.length;
    open.by_status = tally(statusKey);
    if (stageKey) open.by_stage = tally(stageKey);
    if (typeKey) open.by_type = tally(typeKey);
    const closed = /won|sold|lost|closed|cancel|complete|declin|dead|void/i;
    const openByStatus = statusKey ? recs.filter((x) => x[statusKey] && !closed.test(String(x[statusKey]))).length : null;
    const openByDates = wonKey && lostKey ? recs.filter((x) => !x[wonKey] && !x[lostKey]).length : null;
    open.open_in_sample_by_status = openByStatus;
    open.open_in_sample_by_dates = openByDates;

    // exact total, if the dates filter works
    if (wonKey && lostKey) {
      const e = await get(`/Opportunities?${qs({ $filter: `${wonKey} eq null and ${lostKey} eq null`, $top: '0', $count: 'true' })}`);
      const n = e.json && Number(e.json['@odata.count']);
      if (e.status === 200 && Number.isFinite(n)) open.total_open_by_dates = n;
    }
    if (resources.OpportunityStatuses?.exists === true) {
      const s = await get(`/OpportunityStatuses?${qs({ $top: '100' })}`);
      const sr = records(s.json) || [];
      const nameKey = sr[0] && Object.keys(sr[0]).find((k) => /name/i.test(k));
      open.status_list = nameKey ? sr.map((x) => x[nameKey]) : sr.length ? 'returned, no name field' : [];
    }
    const openCount = Math.max(openByStatus ?? 0, openByDates ?? 0, open.total_open_by_dates ?? 0);
    open.answer = openCount > 0
      ? `yes. open opportunities are in there (${openCount} found by ${openByDates ? 'blank won and lost dates' : 'status'}${open.total_open_by_dates !== undefined ? `, ${open.total_open_by_dates} total by the dates filter` : ''})`
      : recs.length ? 'no open ones in the sample. Only sold or lost work came back. See by_status.' : 'no opportunities came back';
  }

  // ---------- 4. who is the rep, what is the branch ----------
  if (samples.Opportunities) {
    const keys = Object.keys(samples.Opportunities);
    const r = await get(`/Opportunities?${qs({ $top: '50' })}`);
    const recs = records(r.json) || [samples.Opportunities];
    const describe = (k: string) => {
      const vals = recs.map((x) => x[k]).filter((v) => v !== null && v !== undefined && v !== '');
      return { field: k, type: typeOf(recs.find((x) => x[k] != null)?.[k]), filled: `${vals.length} of ${recs.length}`, distinct: new Set(vals.map(String)).size, examples: [...new Set(vals.map(String))].slice(0, 3) };
    };
    ids.rep = keys.filter((k) => /sales.?rep|salesperson|sales.?person|estimator|account.?manager|owner|assigned|^rep|employee|user(id|name)?$/i.test(k)).map(describe);
    ids.branch = keys.filter((k) => /branch|office|region|location/i.test(k)).map(describe);
    ids.division = keys.filter((k) => /division/i.test(k)).map(describe);
    ids.other_person_fields = keys.filter((k) => /contact|manager/i.test(k) && !ids.rep.some((x: any) => x.field === k)).slice(0, 12);
  }
  for (const name of ['Divisions', 'Branches']) {
    const s = samples[name];
    if (!s) continue;
    const r = await get(`${resources[name].path}?${qs({ $top: '50' })}`);
    const recs = records(r.json) || [];
    const idKey = Object.keys(s).find((k) => /id$/i.test(k));
    const nameKey = Object.keys(s).find((k) => /name/i.test(k));
    ids[`${name.toLowerCase()}_list`] = recs.map((x) => ({ id: idKey ? x[idKey] : undefined, name: nameKey ? x[nameKey] : undefined }));
  }

  return finish();

  function finish() {
    const summary: string[] = [];
    if (auth.worked) summary.push(`Auth: ${auth.worked.endpoint} with ${auth.worked.body}. Token in "${auth.worked.token_field}", sent as ${auth.worked.header}.`);
    else summary.push('Auth: nothing worked. See auth.attempts.');
    for (const [n, r] of Object.entries<any>(resources || {})) {
      if (r.exists === true) summary.push(`${n}: ${r.path}, ${r.count ?? 'count unknown'} records, ${r.fields?.length ?? 0} fields, modified-since ${r.modified_since?.supported === true ? `yes (${r.modified_since.field})` : r.modified_since?.supported === false ? 'no' : 'unknown'}.`);
      else summary.push(`${n}: ${r.exists || 'not found'} (tried ${r.tried.map((t: any) => `${t.path} ${t.status}`).join(', ')}).`);
    }
    if (open.answer) summary.push(`Open opportunities: ${open.answer}.`);
    if (ids.rep?.length) summary.push(`Rep on an opportunity: ${ids.rep.map((x: any) => x.field).join(', ')}.`);
    if (ids.branch?.length || ids.division?.length) summary.push(`Branch or division: ${[...(ids.branch || []), ...(ids.division || [])].map((x: any) => x.field).join(', ')}.`);
    c.tail(summary);
    return { pass: 1, ...c.footer(), summary, auth, resources, open_opportunities: open, identifiers: ids, notes, log };
  }
}

// ======================= probe2.ts =======================
// Aspire discovery probe, pass 2: can the weekly measures come from Aspire?
// Site audits and client visits, plus who owns a deal. Reads only, writes nothing.
//
// Pass 1 answered the pipeline question (Aspire holds sold work), so this pass does
// not repeat those resources. It spends the call budget in priority order: deal
// ownership first, then site audits, then the activity-like endpoints. If the budget
// runs out, the least likely endpoints are the ones skipped, and the report says so.
//
// Values are shown only for the person fields (with counts, so it is clear whether
// real rep names appear) and for lookup tables such as activity types.


// Aspire's names are inconsistent: each entry is tried in order, first hit wins.
// kind "lookup": a small list of types or categories. Its names are listed, nothing else.
export const PASS2_RESOURCES = [
  { name: 'SiteAudits', paths: ['/SiteAudits', '/SiteAudit', '/PropertyAudits', '/PropertyAudit', '/Audits'] },
  { name: 'Activities', paths: ['/Activities', '/Activity'] },
  { name: 'ContactActivities', paths: ['/ContactActivities', '/ContactActivity'] },
  { name: 'Meetings', paths: ['/Meetings', '/Meeting'] },
  { name: 'Events', paths: ['/Events', '/Event'] },
  { name: 'SiteAuditTypes', paths: ['/SiteAuditTypes', '/SiteAuditType', '/AuditTypes'], kind: 'lookup' },
  { name: 'ActivityTypes', paths: ['/ActivityTypes', '/ActivityType'], kind: 'lookup' },
  { name: 'ActivityCategories', paths: ['/ActivityCategories', '/ActivityCategory'], kind: 'lookup' },
  { name: 'Tasks', paths: ['/Tasks', '/Task'] },
  { name: 'Notes', paths: ['/Notes', '/Note'] },
  { name: 'PropertyContacts', paths: ['/PropertyContacts', '/PropertyContact'] },
  { name: 'Schedules', paths: ['/Schedules', '/Schedule'] },
  { name: 'WorkTickets', paths: ['/WorkTickets', '/WorkTicket'] },
];

// who created or performed it
const PERSON_RE = /((created|performed|completed|assigned|entered|owner|author|auditor|conducted|scheduled|updated|modified|last).*(by|user|contact|employee|name))|^(by|user|employee|salesrep|rep|auditor|owner)|(by|user|employee|rep|owner|auditor)(id|name)?$|(contact|employee|user).?name$/i;
// the business date, not bookkeeping: tried before created and modified dates
const WHEN_RE = /audit|activity|visit|meeting|event|start|scheduled|complete|due|performed|occur|^date$|date$/i;
const BOOKKEEPING_RE = /modif|updat|changed|created|edited|entered/i;
const MODIFIED_RE = /modif|updat|changed|lastedit|edited/i;

const quote = (v: unknown) => (typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
function tallyOf(rows: any[], k: string) {
  const t: Record<string, number> = {};
  for (const r of rows) { const v = r[k] === null || r[k] === undefined || r[k] === '' ? '(blank)' : String(r[k]); t[v] = (t[v] || 0) + 1; }
  return Object.fromEntries(Object.entries(t).sort((a, b) => b[1] - a[1]));
}
const isNameLike = (rows: any[], k: string) => rows.some((r) => typeof r[k] === 'string' && r[k] !== '' && !/^\d+$/.test(r[k]));

export async function probe2(opts: ProbeOptions) {
  const c = await openAspire(opts);
  const { now, auth, get, log } = c;
  const notes: string[] = [];
  const resources: any = {};
  const ownership: any = { answer: 'unknown' };
  if (!c.authed) {
    notes.push('No auth handshake worked. Nothing past this point ran. Check the attempts list for the status each path returned.');
    return finish();
  }

  // ---------- 1. deal ownership: 500 opportunities, distinct rep names with counts ----------
  {
    const first = await get(`/Opportunities?${qs({ $top: '1' })}`);
    const keys = Object.keys((records(first.json) || [])[0] || {});
    const repName = keys.find((k) => /^salesrepcontactname$/i.test(k)) || keys.find((k) => /sales.?rep.*name|salesperson|estimator.*name/i.test(k)) || null;
    const repId = keys.find((k) => /^salesrepcontactid$/i.test(k)) || keys.find((k) => /sales.?rep.*id/i.test(k)) || null;
    const status = keys.find((k) => /^(opportunity)?status(name)?$/i.test(k)) || keys.find((k) => /status.*name/i.test(k)) || null;
    const order = keys.find((k) => MODIFIED_RE.test(k)) || keys.find((k) => /won.?date/i.test(k)) || null;
    ownership.fields = { rep_name: repName, rep_id: repId, status, ordered_by: order ? `${order} desc` : 'unordered' };
    const select = [repName, repId, status].filter(Boolean).join(',');
    const rows: any[] = [];
    let pageCap: number | null = null;
    let selectOk = !!select;
    let top = 500;
    let firstKey = '';
    for (let page = 0; page < 6 && rows.length < 500; page++) {
      const want = Math.min(top, 500 - rows.length);
      const q: Record<string, string> = { $top: String(want) };
      if (rows.length) q.$skip = String(rows.length);
      if (selectOk) q.$select = select;
      if (order) q.$orderby = `${order} desc`;
      let r = await get(`/Opportunities?${qs(q)}`);
      if (r.status === 400 && selectOk) { selectOk = false; delete q.$select; r = await get(`/Opportunities?${qs(q)}`); }
      if (r.status === 400 && page === 0 && top > 100) { top = 100; q.$top = '100'; r = await get(`/Opportunities?${qs(q)}`); ownership.note = 'Aspire refused $top=500, so pages of 100'; }
      const batch = records(r.json);
      if (r.status !== 200 || !batch) { ownership.stopped = `page ${page + 1} returned ${r.status}`; break; }
      if (!batch.length) break;
      const key = JSON.stringify(batch[0]);
      if (page === 0) firstKey = key;
      else if (key === firstKey) { ownership.stopped = 'Aspire ignored $skip and sent the first page again, so only the first page is counted'; break; }
      rows.push(...batch);
      if (page === 0 && batch.length < want) pageCap = batch.length;
      if (batch.length < (pageCap ?? want)) break; // a short page is the last page
    }
    ownership.pulled = rows.length;
    if (pageCap && pageCap < 500) ownership.page_size_cap = pageCap;
    if (repName) {
      const t = tallyOf(rows, repName);
      ownership.distinct_rep_names = Object.keys(t).filter((k) => k !== '(blank)').length;
      ownership.rep_names_with_counts = t;
    }
    if (repId) ownership.distinct_rep_ids = Object.keys(tallyOf(rows, repId)).filter((k) => k !== '(blank)').length;
    if (status) ownership.by_status = tallyOf(rows, status);
    ownership.answer = !repName ? 'no sales rep field found on opportunities'
      : !rows.length ? 'no opportunities came back'
      : `${ownership.distinct_rep_names} distinct rep names across ${rows.length} opportunities. Check rep_names_with_counts against the roster.`;
  }

  // ---------- 2. each candidate resource ----------
  for (const res of PASS2_RESOURCES) {
    const out: any = { exists: false, path: null, tried: [] };
    resources[res.name] = out;
    let sample: any = null;
    for (const p of res.paths) {
      let r = await get(`${p}?${qs({ $top: '1' })}`);
      // some endpoints refuse OData options but answer a bare GET
      if (r.status === 400) { out.tried.push({ path: `${p}?$top=1`, status: 400 }); r = await get(p); }
      out.tried.push({ path: p, status: r.status });
      if (r.skipped) break;
      if (r.status === 401 || r.status === 403) { out.exists = 'probably, but this credential is not allowed to read it'; out.path = p; break; }
      if (r.status >= 200 && r.status < 300) {
        const recs = records(r.json);
        out.exists = true; out.path = p;
        if (recs === null) { out.note = 'responded, but not with a list of records'; break; }
        sample = recs[0] || null;
        out.fields = fieldsOf(sample);
        if (!sample) out.note = 'exists, but returned no records';
        break;
      }
    }
    if (out.exists !== true || !sample) continue;
    const keys = Object.keys(sample);

    if (res.kind === 'lookup') {
      const r = await get(`${out.path}?${qs({ $top: '100' })}`);
      const rows = records(r.json) || [sample];
      const nameKey = keys.find((k) => /name|description|title/i.test(k));
      const idKey = keys.find((k) => /id$/i.test(k));
      out.values = rows.map((x) => ({ id: idKey ? x[idKey] : undefined, name: nameKey ? x[nameKey] : undefined }));
      continue;
    }

    // the date field, and the range of the 50 most recent records
    const dates = out.fields.filter((x: any) => x.type === 'date').map((x: any) => x.name);
    const when = dates.find((k: string) => WHEN_RE.test(k) && !BOOKKEEPING_RE.test(k)) || dates.find((k: string) => /created/i.test(k)) || dates.find((k: string) => MODIFIED_RE.test(k)) || null;
    const modified = keys.find((k) => MODIFIED_RE.test(k)) || null;
    out.date_fields = dates;
    out.date_field = when;

    let recent: any[] = [];
    if (when) {
      let r = await get(`${out.path}?${qs({ $top: '50', $orderby: `${when} desc` })}`);
      out.recent_ordered = r.status === 200 && !!records(r.json);
      if (!out.recent_ordered) r = await get(`${out.path}?${qs({ $top: '50' })}`);
      recent = records(r.json) || [];
      const vals = recent.map((x) => x[when]).filter((v) => typeof v === 'string').sort();
      out.recent_50 = { returned: recent.length, ordered: out.recent_ordered ? `${when} desc` : 'no, the order would not apply', oldest: vals[0] || null, newest: vals[vals.length - 1] || null };
    } else {
      const r = await get(`${out.path}?${qs({ $top: '50' })}`);
      recent = records(r.json) || [];
      out.recent_50 = { returned: recent.length, note: 'no date field on the sample record' };
    }
    const rows = recent.length ? recent : [sample];

    // who created or performed it, with values and counts
    const people = keys.filter((k) => PERSON_RE.test(k) && !/date|time/i.test(k));
    out.person_fields = people.map((k) => ({ field: k, type: typeOf(rows.find((x) => x[k] != null)?.[k]), names: isNameLike(rows, k), values_in_recent: tallyOf(rows, k) }));

    // what kind of record each one is (e.g. a "Client Visit" activity type), counted in the recent 50
    const kinds = keys.filter((k) => /type|category|kind|reason|purpose/i.test(k) && isNameLike(rows, k));
    out.type_fields = kinds.map((k) => ({ field: k, values_in_recent: tallyOf(rows, k) }));

    // can it be filtered by date? a year-2100 cutoff has to come back empty
    const future = '2100-01-01T00:00:00Z';
    const dateTest = async (field: string) => {
      const r = await get(`${out.path}?${qs({ $filter: `${field} ge ${future}`, $top: '1' })}`);
      const got = records(r.json);
      if (r.status !== 200 || got === null) return { field, supported: false, why: `$filter on ${field} returned ${r.status}` };
      if (got.length > 0) return { field, supported: false, why: 'accepted but ignored: a year-2100 cutoff still returned records' };
      return { field, supported: true, syntax: `$filter=${field} ge <date>` };
    };
    out.date_filter = when ? await dateTest(when) : { supported: 'unknown', why: 'no date field' };
    if (modified && modified !== when) out.modified_filter = await dateTest(modified);
    else if (modified) out.modified_filter = out.date_filter;

    // can it be filtered by person? every row that comes back has to match
    const pf = out.person_fields.find((x: any) => x.names) || out.person_fields[0];
    const example = pf && Object.keys(pf.values_in_recent).find((v) => v !== '(blank)');
    if (!pf || !example) out.person_filter = { supported: 'unknown', why: 'no person field with a value to test' };
    else {
      const raw = rows.find((x) => String(x[pf.field]) === example)?.[pf.field];
      const r = await get(`${out.path}?${qs({ $filter: `${pf.field} eq ${quote(raw)}`, $top: '20' })}`);
      const got = records(r.json);
      if (r.status !== 200 || got === null) out.person_filter = { field: pf.field, supported: false, why: `$filter on ${pf.field} returned ${r.status}` };
      else if (!got.length) out.person_filter = { field: pf.field, supported: 'unclear', why: 'filter accepted but returned nothing for a value seen in the data' };
      else if (got.some((x) => String(x[pf.field]) !== example)) out.person_filter = { field: pf.field, supported: false, why: 'accepted but ignored: rows for other people came back' };
      else out.person_filter = { field: pf.field, supported: true, syntax: `$filter=${pf.field} eq ${typeof raw === 'number' ? '<id>' : "'<name>'"}` };
    }
  }

  return finish();

  function finish() {
    const summary: string[] = [];
    if (!auth.worked) summary.push('Auth: nothing worked. See auth.attempts.');
    else summary.push(`Auth: ${auth.worked.endpoint}, sent as ${auth.worked.header}.`);
    if (ownership.answer) summary.push(`Deal ownership: ${ownership.answer}${ownership.page_size_cap ? ` Aspire pages at ${ownership.page_size_cap}.` : ''}`);
    for (const [n, r] of Object.entries<any>(resources)) {
      if (r.exists !== true) { summary.push(`${n}: ${r.exists || 'not found'} (tried ${r.tried.map((t: any) => `${t.path} ${t.status}`).join(', ')}).`); continue; }
      if (r.values) { summary.push(`${n}: ${r.path}, ${r.values.length} values: ${r.values.slice(0, 12).map((v: any) => v.name).join(', ')}.`); continue; }
      if (!r.fields?.length) { summary.push(`${n}: ${r.path}, ${r.note || 'no records'}.`); continue; }
      const who = (r.person_fields || []).filter((x: any) => x.names).map((x: any) => `${x.field} (${Object.keys(x.values_in_recent).filter((v) => v !== '(blank)').length} names)`).join(', ') || 'no name field';
      const range = r.recent_50?.newest ? `${String(r.recent_50.oldest).slice(0, 10)} to ${String(r.recent_50.newest).slice(0, 10)}` : 'no range';
      const yn = (x: any) => (x?.supported === true ? 'yes' : x?.supported === false ? 'no' : 'unclear');
      const kinds = (r.type_fields || []).map((x: any) => `${x.field}: ${Object.entries(x.values_in_recent).slice(0, 6).map(([v, c]) => `${v} ${c}`).join(', ')}`).join('; ');
      summary.push(`${n}: ${r.path}, ${r.fields.length} fields. Date ${r.date_field || 'none'} (recent 50: ${range}), date filter ${yn(r.date_filter)}${r.modified_filter && r.modified_filter !== r.date_filter ? `, modified filter ${yn(r.modified_filter)}` : ''}. Person ${who}, person filter ${yn(r.person_filter)}.${kinds ? ` Kinds in recent 50: ${kinds}.` : ''}`);
    }
    c.tail(summary);
    return { pass: 2, ...c.footer(), summary, auth, deal_ownership: ownership, resources, notes, log };
  }
}

// ======================= probe3.ts =======================
// Aspire discovery probe, pass 3: reconcile Aspire against what Summit holds. Reads only, writes nothing.
//
// Question one, ownership coverage: every opportunity that is not Won or Lost, plus everything Won in
// the last 180 days, grouped by rep and by status, with the rows themselves.
// Question two, activity coverage: activities created in the last 90 days, counted per person per
// calendar week, so it is clear whether logging is a habit or occasional.
//
// Paging is the hard part. Aspire caps page size and ignores $skip in places, so every pull pages by
// key (ID gt the last ID seen, ordered by ID) and falls back to $skip only when the key trick fails.
// Every row is checked again here, so a filter Aspire accepts but ignores cannot inflate a count.
// The paging report says exactly what happened.


export const OPP_FIELDS = [
  'OpportunityID', 'OpportunityNumber', 'OpportunityName', 'PropertyName', 'SalesRepContactName', 'BranchName',
  'DivisionName', 'OpportunityStatusName', 'EstimatedDollars', 'WonDollars', 'StartDate', 'AnticipatedCloseDate',
  'WonDate', 'ModifiedDate',
];
export const WON_DAYS = 180;
export const ACTIVITY_DAYS = 90;
const MAX_PAGES = 100;

type Get = (p: string) => Promise<any>;
const lit = (v: unknown) => (typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const day10 = (v: unknown) => (typeof v === 'string' && /^\d{4}-\d{2}-\d{2}/.test(v) ? v.slice(0, 10) : null);
const money = (v: unknown) => (Number.isFinite(Number(v)) ? Number(v) : 0);
const round2 = (n: number) => Math.round(n * 100) / 100;
const usd = (n: number) => '$' + Math.round(n).toLocaleString('en-US');
const filled = (v: unknown) => v !== null && v !== undefined && v !== '' && v !== 0;
const cmp = (a: any, b: any) => (typeof a === 'number' && typeof b === 'number' ? a - b : String(a) < String(b) ? -1 : String(a) > String(b) ? 1 : 0);
const ascending = (rows: any[], k: string) => rows.every((r, i) => i === 0 || cmp(rows[i - 1][k], r[k]) < 0);
const findKey = (keys: string[], ...tests: RegExp[]) => { for (const t of tests) { const k = keys.find((x) => t.test(x)); if (k) return k; } return null; };

// Monday-start calendar week of a YYYY-MM-DD date
export function weekOf(d: string) {
  const t = Date.UTC(+d.slice(0, 4), +d.slice(5, 7) - 1, +d.slice(8, 10));
  const dow = new Date(t).getUTCDay();
  return new Date(t - ((dow + 6) % 7) * 86400000).toISOString().slice(0, 10);
}
export function weeksBetween(from: string, to: string) {
  const out: string[] = [];
  for (let w = weekOf(from); w <= weekOf(to); w = new Date(Date.parse(w + 'T00:00:00Z') + 7 * 86400000).toISOString().slice(0, 10)) out.push(w);
  return out;
}

interface Pull {
  path: string;
  idKey: string;
  filters: (string | null)[]; // tried in order; null means no filter, rows checked here instead
  select?: string[];
  keep: (row: any) => boolean;
  startTop?: number;
}

// Pulls every row a filter matches, whatever Aspire's paging does, and says what it did.
export async function pullAll(get: Get, spec: Pull) {
  const p: any = { filter_used: undefined, filters_refused: [], requested_top: spec.startTop ?? 1000, pages: 0, notes: [] };
  const seen = new Map<string, any>();
  let dupes = 0;
  let settings: { f: string | null; sel: boolean; ord: boolean; top: number } | null = null;
  let batch: any[] = [];

  const build = (s: typeof settings, extra: { after?: unknown; skip?: number } = {}) => {
    const q: Record<string, string> = { $top: String(s!.top) };
    const key = extra.after !== undefined ? `${spec.idKey} gt ${lit(extra.after)}` : null;
    const f = s!.f && key ? `(${s!.f}) and ${key}` : s!.f || key;
    if (f) q.$filter = f;
    if (s!.sel && spec.select?.length) q.$select = spec.select.join(',');
    if (s!.ord) q.$orderby = `${spec.idKey} asc`;
    if (extra.skip) q.$skip = String(extra.skip);
    return `${spec.path}?${qs(q)}`;
  };
  const take = (rows: any[]) => {
    let fresh = 0;
    for (const r of rows) { const id = String(r[spec.idKey]); if (seen.has(id)) dupes++; else { seen.set(id, r); fresh++; } }
    return fresh;
  };

  // 1. first page: find a filter Aspire accepts, then the richest query shape it accepts
  const top = p.requested_top;
  outer: for (const f of spec.filters) {
    const ladder = [
      { f, sel: !!spec.select?.length, ord: true, top },
      { f, sel: false, ord: true, top },
      { f, sel: false, ord: true, top: 100 },
      { f, sel: false, ord: false, top: 100 },
    ].filter((v, i, a) => a.findIndex((x) => x.sel === v.sel && x.ord === v.ord && x.top === v.top) === i);
    for (const s of ladder) {
      const r = await get(build(s));
      if (r.skipped) { p.stopped = 'the call or time budget ran out before the first page'; break outer; }
      const recs = records(r.json);
      if (r.status === 200 && recs) { settings = s; batch = recs; if (r.json?.['@odata.nextLink']) p.next_link_offered = true; break outer; }
      if (r.status !== 400 && r.status < 500) { p.stopped = `first page returned ${r.status}`; break outer; }
    }
    p.filters_refused.push(f ?? '(no filter)');
  }
  if (!settings) { p.stopped ??= 'every filter and query shape was refused'; return { rows: [], paging: p }; }
  p.filter_used = settings.f ?? 'none. Aspire refused every filter, so rows were checked here instead';
  p.select_used = settings.sel;
  p.ordered_by_id = settings.ord;
  if (settings.top !== top) p.notes.push(`Aspire refused $top=${top}, so pages ask for ${settings.top}`);
  p.pages = 1;
  take(batch);
  let largest = batch.length;

  // what Aspire says the total is, to check the pull against
  {
    const q: Record<string, string> = { $top: '1', $count: 'true' };
    if (settings.f) q.$filter = settings.f;
    const r = await get(`${spec.path}?${qs(q)}`);
    const n = Number(r.json?.['@odata.count'] ?? r.json?.Count ?? r.json?.count);
    p.aspire_count = r.status === 200 && Number.isFinite(n) && r.json && ('@odata.count' in r.json || 'Count' in r.json || 'count' in r.json) ? n : null;
  }

  // 2. the rest: by key when the order held, by $skip when it did not
  let mode: 'key' | 'skip' = settings.ord && ascending(batch, spec.idKey) ? 'key' : 'skip';
  if (settings.ord && mode === 'skip') p.notes.push('$orderby was accepted but the first page was not in ID order, so paging by key is unsafe');
  p.method = mode === 'key' ? `by key: ${spec.idKey} gt <last ID>, ordered by ${spec.idKey}` : '$skip';
  while (p.pages < MAX_PAGES && batch.length && !(p.pages > 1 && batch.length < largest)) {
    if (p.aspire_count != null && seen.size >= p.aspire_count) break; // Aspire's own total is reached
    let r: any;
    if (mode === 'key') {
      const last = batch[batch.length - 1][spec.idKey];
      r = await get(build(settings, { after: last }));
      const recs = records(r.json);
      if (r.skipped) { p.stopped = 'the call or time budget ran out mid-pull. The rows above are real but incomplete'; break; }
      if (r.status !== 200 || !recs) { p.notes.push(`paging by key was refused (${r.status}), switched to $skip`); mode = 'skip'; p.method = `by key, then $skip after page ${p.pages}`; continue; }
      if (recs.length && (!ascending(recs, spec.idKey) || cmp(recs[0][spec.idKey], last) <= 0)) {
        p.notes.push(`Aspire ignored "${spec.idKey} gt" on page ${p.pages + 1}, switched to $skip`);
        mode = 'skip'; p.method = `by key, then $skip after page ${p.pages}`; continue;
      }
      batch = recs;
    } else {
      r = await get(build(settings, { skip: seen.size }));
      const recs = records(r.json);
      if (r.skipped) { p.stopped = 'the call or time budget ran out mid-pull. The rows above are real but incomplete'; break; }
      if (r.status !== 200 || !recs) { p.stopped = `page ${p.pages + 1} returned ${r.status}`; break; }
      batch = recs;
      if (batch.length && batch.every((x) => seen.has(String(x[spec.idKey])))) {
        p.stopped = `Aspire ignored $skip and sent rows it had already sent. Only ${seen.size} rows could be read this way`;
        p.skip_ignored = true;
        break;
      }
    }
    p.pages++;
    take(batch);
    largest = Math.max(largest, batch.length);
  }
  if (p.pages >= MAX_PAGES) p.stopped ??= `stopped at the ${MAX_PAGES}-page safety cap`;
  if (largest < settings.top && p.pages > 1) p.page_size_cap = largest;
  p.duplicates_dropped = dupes;
  p.rows_pulled = seen.size;
  const all = [...seen.values()];
  const rows = all.filter(spec.keep);
  p.rows_kept = rows.length;
  p.rows_failed_check = all.length - rows.length;
  if (p.rows_failed_check && settings.f) p.notes.push(`${p.rows_failed_check} rows did not match the filter, so Aspire did not fully apply it. They were dropped here`);
  if (p.aspire_count != null) p.matches_aspire_count = seen.size === p.aspire_count;
  if (!p.notes.length) delete p.notes;
  return { rows, paging: p };
}

// ---------- question one ----------
async function ownership(get: Get, now: Date) {
  const out: any = {};
  const first = await get(`/Opportunities?${qs({ $top: '1' })}`);
  const sample = (records(first.json) || [])[0];
  if (!sample) { out.stopped = `could not read an opportunity (${first.status})`; return out; }
  const keys = Object.keys(sample);
  out.missing_fields = OPP_FIELDS.filter((f) => !keys.includes(f));
  const idKey = keys.includes('OpportunityID') ? 'OpportunityID' : findKey(keys, /^opportunityid$/i, /id$/i) || keys[0];
  const statusKey = keys.includes('OpportunityStatusName') ? 'OpportunityStatusName' : findKey(keys, /status.*name/i, /status/i);
  const wonKey = keys.includes('WonDate') ? 'WonDate' : findKey(keys, /^won.?date$/i);
  const lostKey = findKey(keys, /^lost.?date$/i);
  const cutoff = new Date(now.getTime() - WON_DAYS * 86400000).toISOString().slice(0, 10);
  out.won_since = cutoff;

  const status = (r: any) => String(r[statusKey!] ?? '').trim();
  const isWon = (r: any) => /^won$/i.test(status(r));
  const isLost = (r: any) => /^lost$/i.test(status(r));
  const select = [...new Set([idKey, statusKey, wonKey, lostKey, ...OPP_FIELDS.filter((f) => keys.includes(f))].filter(Boolean))] as string[];
  const wonRecently = (r: any) => !!wonKey && (day10(r[wonKey]) ?? '') >= cutoff;
  const isOpen = (r: any) => (statusKey ? !isWon(r) && !isLost(r) : !r[wonKey!] && !(lostKey && r[lostKey])) && !wonRecently(r);

  const openFilters: (string | null)[] = [];
  if (statusKey) openFilters.push(`${statusKey} ne 'Won' and ${statusKey} ne 'Lost'`);
  if (wonKey && lostKey) openFilters.push(`${wonKey} eq null and ${lostKey} eq null`);
  openFilters.push(null);
  const open = await pullAll(get, { path: '/Opportunities', idKey, filters: openFilters, select, keep: isOpen });

  let won = { rows: [] as any[], paging: { stopped: 'no won date field on opportunities' } as any };
  if (wonKey) {
    won = await pullAll(get, {
      path: '/Opportunities', idKey, select, keep: wonRecently,
      filters: [`${wonKey} ge ${cutoff}T00:00:00Z`, `${wonKey} ge ${cutoff}T00:00:00`, null],
    });
  }
  out.paging = { open: open.paging, won_last_180_days: won.paging };

  const byId = new Map<string, any>();
  for (const r of open.rows) byId.set(String(r[idKey]), { ...r, bucket: 'open' });
  for (const r of won.rows) byId.set(String(r[idKey]), { ...r, bucket: 'won_180' });
  const rows = [...byId.values()].map((r) => ({ ...Object.fromEntries(OPP_FIELDS.map((f) => [f, r[f] ?? null])), bucket: r.bucket }));

  const repKey = 'SalesRepContactName';
  const reps = new Map<string, any>();
  const statuses = new Map<string, any>();
  for (const r of rows) {
    const rep = r[repKey] ? String(r[repKey]) : '(no rep)';
    const g = reps.get(rep) || { rep, total_count: 0, open_count: 0, open_estimated: 0, won_count: 0, won_dollars: 0 };
    g.total_count++;
    if (r.bucket === 'open') { g.open_count++; g.open_estimated += money(r.EstimatedDollars); }
    else { g.won_count++; g.won_dollars += money(r.WonDollars); }
    reps.set(rep, g);
    const st = r.OpportunityStatusName ? String(r.OpportunityStatusName) : '(blank)';
    const s = statuses.get(st) || { status: st, count: 0, estimated: 0, won_dollars: 0 };
    s.count++; s.estimated += money(r.EstimatedDollars); s.won_dollars += money(r.WonDollars);
    statuses.set(st, s);
  }
  const fix = (o: any) => Object.fromEntries(Object.entries(o).map(([k, v]) => [k, typeof v === 'number' ? round2(v) : v]));
  out.totals = fix({
    opportunities: rows.length,
    open: rows.filter((r) => r.bucket === 'open').length,
    open_estimated: rows.filter((r) => r.bucket === 'open').reduce((a, r) => a + money(r.EstimatedDollars), 0),
    won_last_180_days: rows.filter((r) => r.bucket === 'won_180').length,
    won_dollars: rows.filter((r) => r.bucket === 'won_180').reduce((a, r) => a + money(r.WonDollars), 0),
    no_rep: rows.filter((r) => !r[repKey]).length,
  });
  out.by_rep = [...reps.values()].map(fix).sort((a: any, b: any) => b.total_count - a.total_count);
  out.by_status = [...statuses.values()].map(fix).sort((a: any, b: any) => b.count - a.count);
  out.rows = rows;
  return out;
}

// ---------- question two ----------
async function activity(get: Get, now: Date) {
  const out: any = { tried: [] };
  let path: string | null = null;
  let sample: any = null;
  for (const p of ['/Activities', '/Activity']) {
    const r = await get(`${p}?${qs({ $top: '1' })}`);
    out.tried.push({ path: p, status: r.status });
    const recs = records(r.json);
    if (r.status === 200 && recs) { path = p; sample = recs[0]; break; }
    if (r.skipped) break;
  }
  if (!path || !sample) { out.stopped = path ? 'the activities endpoint returned no records' : 'no activities endpoint answered'; return out; }
  out.path = path;
  const keys = Object.keys(sample);
  const idKey = findKey(keys, /^activityid$/i, /^id$/i, /id$/i) || keys[0];
  const who = findKey(keys, /^createdbyusername$/i, /created.?by.*name/i, /created.?by/i);
  const when = findKey(keys, /^createddate$/i, /^created.?(date|on|datetime|time)$/i, /created.*date/i);
  const cat = findKey(keys, /^activitycategoryname$/i, /category.*name/i, /category/i);
  const kind = findKey(keys, /^activitytypename$/i, /activity.?type.*name/i, /^activitytype$/i);
  const prop = findKey(keys, /^propertyid$/i);
  const opp = findKey(keys, /^opportunityid$/i);
  out.fields = { id: idKey, person: who, date: when, category: cat, type: kind, property: prop, opportunity: opp };
  if (!when) { out.stopped = 'no created date field on activities, so there is nothing to count by week'; out.sample_fields = keys; return out; }

  const since = new Date(now.getTime() - ACTIVITY_DAYS * 86400000).toISOString().slice(0, 10);
  const today = now.toISOString().slice(0, 10);
  out.since = since;
  const pulled = await pullAll(get, {
    path, idKey, keep: (r) => (day10(r[when]) ?? '') >= since,
    filters: [`${when} ge ${since}T00:00:00Z`, `${when} ge ${since}T00:00:00`, null],
  });
  out.paging = pulled.paging;
  const rows = pulled.rows;
  out.activities = rows.length;

  // per person per calendar week (Monday start). The first and current weeks are partial.
  const weeks = weeksBetween(since, today);
  out.weeks_in_window = weeks.length;
  out.week_note = `Weeks start Monday, by ${when}. The first week (${weeks[0]}) and the current week (${weeks[weeks.length - 1]}) are partial.`;
  const people = new Map<string, Record<string, number>>();
  for (const r of rows) {
    const p = who && r[who] ? String(r[who]) : '(blank)';
    const w = weekOf(day10(r[when])!);
    const m = people.get(p) || Object.fromEntries(weeks.map((x) => [x, 0]));
    m[w] = (m[w] || 0) + 1;
    people.set(p, m);
  }
  out.habit_rule = 'habit: at least one in 75% or more of the weeks. patchy: 50 to 74%. occasional: under 50%.';
  out.by_person = [...people.entries()].map(([person, per]) => {
    const active = Object.values(per).filter((n) => n > 0).length;
    const share = active / weeks.length;
    return {
      person, total: Object.values(per).reduce((a, b) => a + b, 0), weeks_active: active, weeks_in_window: weeks.length,
      share: Math.round(share * 100) / 100, pattern: share >= 0.75 ? 'habit' : share >= 0.5 ? 'patchy' : 'occasional', per_week: per,
    };
  }).sort((a, b) => b.weeks_active - a.weeks_active || b.total - a.total);

  // category filled or blank
  if (cat) {
    const t: Record<string, number> = {};
    for (const r of rows) if (filled(r[cat])) t[String(r[cat])] = (t[String(r[cat])] || 0) + 1;
    const n = Object.values(t).reduce((a, b) => a + b, 0);
    out.category = { field: cat, filled: n, blank: rows.length - n, values: Object.fromEntries(Object.entries(t).sort((a, b) => b[1] - a[1])) };
  } else out.category = { field: null, note: 'no category field on activities' };
  if (kind) {
    const t: Record<string, number> = {};
    for (const r of rows) { const v = filled(r[kind]) ? String(r[kind]) : '(blank)'; t[v] = (t[v] || 0) + 1; }
    out.type = { field: kind, values: Object.fromEntries(Object.entries(t).sort((a, b) => b[1] - a[1])) };
  }

  // linked to a property or an opportunity, or floating
  const L: any = { property_field: prop, opportunity_field: opp, property_only: 0, opportunity_only: 0, both: 0, floating: 0 };
  const otherLinks = keys.filter((k) => /id$/i.test(k) && ![idKey, prop, opp].includes(k) && !/created|modified|updated|user|owner|assigned|category|type|status|priority/i.test(k));
  const floatOther: Record<string, number> = {};
  let floatBare = 0;
  for (const r of rows) {
    const hp = !!prop && filled(r[prop]);
    const ho = !!opp && filled(r[opp]);
    if (hp && ho) L.both++; else if (hp) L.property_only++; else if (ho) L.opportunity_only++;
    else {
      L.floating++;
      const hits = otherLinks.filter((k) => filled(r[k]));
      for (const k of hits) floatOther[k] = (floatOther[k] || 0) + 1;
      if (!hits.length) floatBare++;
    }
  }
  L.floating_but_linked_to = floatOther;
  L.floating_with_no_link_at_all = floatBare;
  if (!prop || !opp) L.note = `not on the record: ${[!prop && 'PropertyID', !opp && 'OpportunityID'].filter(Boolean).join(', ')}`;
  out.links = L;
  return out;
}

export type Pass3Part = 'ownership' | 'activity' | 'both';

export async function probe3(opts: ProbeOptions & { part?: Pass3Part }) {
  const c = await openAspire({ maxCalls: 300, ...opts });
  const { now, auth, get, log } = c;
  const part = opts.part || 'both';
  const notes: string[] = [];
  let own: any = null;
  let act: any = null;
  if (!c.authed) notes.push('No auth handshake worked. Nothing past this point ran.');
  else {
    if (part !== 'activity') own = await ownership(get, now);
    if (part !== 'ownership') act = await activity(get, now);
  }

  const summary: string[] = [];
  summary.push(auth.worked ? `Auth: ${auth.worked.endpoint}, sent as ${auth.worked.header}.` : 'Auth: nothing worked. See auth.attempts.');
  const pageLine = (label: string, p: any) => p && summary.push(
    `  ${label}: ${p.rows_kept ?? 0} rows, ${p.pages} page(s), ${p.method || 'no paging'}${p.page_size_cap ? `, Aspire caps pages at ${p.page_size_cap}` : ''}` +
    `${p.aspire_count != null ? `, Aspire count ${p.aspire_count}${p.matches_aspire_count ? ' (matches)' : ' (DOES NOT match)'}` : ''}` +
    `${p.duplicates_dropped ? `, ${p.duplicates_dropped} duplicates dropped` : ''}${p.rows_failed_check ? `, ${p.rows_failed_check} failed the check` : ''}` +
    `. Filter: ${p.filter_used ?? 'none worked'}.${p.stopped ? ` Stopped: ${p.stopped}.` : ''}`);
  if (own) {
    if (own.stopped) summary.push(`Ownership: ${own.stopped}.`);
    else {
      const t = own.totals;
      summary.push(`Ownership: ${t.opportunities} opportunities. ${t.open} open (${usd(t.open_estimated)} estimated), ${t.won_last_180_days} won since ${own.won_since} (${usd(t.won_dollars)} won). ${t.no_rep} have no rep.`);
      pageLine('open', own.paging.open);
      pageLine('won', own.paging.won_last_180_days);
      summary.push(`  by rep: ${own.by_rep.map((r: any) => `${r.rep} ${r.open_count} open ${usd(r.open_estimated)} / ${r.won_count} won ${usd(r.won_dollars)}`).join('; ')}.`);
      summary.push(`  by status: ${own.by_status.map((s: any) => `${s.status} ${s.count}`).join(', ')}.`);
      if (own.missing_fields.length) summary.push(`  not on the record: ${own.missing_fields.join(', ')}.`);
    }
  }
  if (act) {
    if (act.stopped) summary.push(`Activity: ${act.stopped}.`);
    else {
      summary.push(`Activity: ${act.activities} created since ${act.since} at ${act.path}, over ${act.weeks_in_window} weeks.`);
      pageLine('activities', act.paging);
      summary.push(`  by person (weeks with at least one): ${act.by_person.map((p: any) => `${p.person} ${p.weeks_active}/${p.weeks_in_window} ${p.pattern} (${p.total})`).join('; ')}.`);
      if (act.category.field) summary.push(`  ${act.category.field}: ${act.category.filled} filled, ${act.category.blank} blank.`);
      const L = act.links;
      summary.push(`  links: ${L.property_only} property only, ${L.opportunity_only} opportunity only, ${L.both} both, ${L.floating} floating (${L.floating_with_no_link_at_all} with no link at all).`);
    }
  }
  c.tail(summary);
  return { pass: 3, part, ...c.footer(), summary, auth, ownership: own, activity: act, notes, log };
}

export function toCsv(rows: any[]) {
  const cols = [...OPP_FIELDS, 'bucket'];
  const cell = (v: unknown) => (v === null || v === undefined ? '' : /[",\n]/.test(String(v)) ? `"${String(v).replace(/"/g, '""')}"` : String(v));
  return [cols.join(','), ...rows.map((r) => cols.map((c) => cell(r[c])).join(','))].join('\n') + '\n';
}

// ======================= gate.ts =======================
// Who may run the probe. Three ways in, checked in order:
//   1. the bearer token equals SUPABASE_SERVICE_ROLE_KEY
//   2. the bearer token is a JWT with role "service_role", and Supabase itself
//      accepts it on an admin-only endpoint (so a hand-made token with that
//      claim but no valid signature is refused)
//   3. the bearer token belongs to a signed-in user with a row in app_admins
// Everyone else is refused, with the result of every check, so a failure says why.
// Never echoes a key or a token. Only its kind and length.

type GateFetch = (url: string, init?: any) => Promise<any>;
export interface GateEnv {
  SUPABASE_URL?: string;
  SUPABASE_ANON_KEY?: string;
  SUPABASE_SERVICE_ROLE_KEY?: string;
}

export function kindOf(t: string | undefined | null) {
  if (!t) return 'not set';
  if (t.startsWith('sb_secret_')) return `new-format secret key (sb_secret_..., ${t.length} chars)`;
  if (t.startsWith('sb_publishable_')) return `new-format publishable key (sb_publishable_..., ${t.length} chars)`;
  if (t.split('.').length === 3) return `JWT (${t.length} chars)`;
  return `opaque string (${t.length} chars)`;
}

export function jwtClaims(t: string): any | null {
  const parts = t.split('.');
  if (parts.length !== 3) return null;
  try {
    const b64 = parts[1].replace(/-/g, '+').replace(/_/g, '/').padEnd(Math.ceil(parts[1].length / 4) * 4, '=');
    return JSON.parse(atob(b64));
  } catch {
    return null;
  }
}

export async function authorize(authHeader: string | null, env: GateEnv, f: GateFetch = (u, i) => fetch(u, i)) {
  const checks: Record<string, string> = {};
  const token = (authHeader || '').replace(/^Bearer\s+/i, '').trim();
  const url = (env.SUPABASE_URL || '').replace(/\/+$/, '');
  if (!token) {
    return { ok: false, via: null, checks: { header: 'no: no Authorization: Bearer <token> header on the request' } };
  }
  checks.token = `received a ${kindOf(token)}`;

  // 1. exact match to the injected service role key
  const svc = env.SUPABASE_SERVICE_ROLE_KEY;
  if (!svc) checks.service_key_match = 'no: SUPABASE_SERVICE_ROLE_KEY is not set in this function';
  else if (token === svc) return { ok: true, via: 'service_key_match', checks: { ...checks, service_key_match: 'yes' } };
  else checks.service_key_match = `no: token differs from SUPABASE_SERVICE_ROLE_KEY, which is a ${kindOf(svc)}`;

  // 2. a JWT that claims service_role, confirmed by Supabase
  const claims = jwtClaims(token);
  if (!claims) checks.service_role_jwt = 'no: token is not a JWT';
  else if (claims.role !== 'service_role') checks.service_role_jwt = `no: JWT role claim is "${claims.role ?? '(none)'}"`;
  else if (!url) checks.service_role_jwt = 'no: role claim is service_role, but SUPABASE_URL is not set, so it could not be confirmed';
  else {
    try {
      const r = await f(`${url}/auth/v1/admin/users?page=1&per_page=1`, { headers: { apikey: token, Authorization: `Bearer ${token}` } });
      if (r.status === 200) return { ok: true, via: 'service_role_jwt', checks: { ...checks, service_role_jwt: 'yes: role claim is service_role and Supabase accepted it' } };
      checks.service_role_jwt = `no: role claim is service_role but Supabase rejected the token (${r.status}). Wrong project, rotated, or not a real key.`;
    } catch (e) {
      checks.service_role_jwt = `no: could not reach ${url} to confirm it (${String((e as any)?.message || e)})`;
    }
  }

  // 3. a signed-in Summit admin
  if (!url) checks.app_admin = 'no: SUPABASE_URL is not set';
  else if (claims && claims.role === 'service_role') checks.app_admin = 'no: token is a service role key, not a user';
  else {
    const apikey = env.SUPABASE_ANON_KEY || token;
    try {
      const u = await f(`${url}/auth/v1/user`, { headers: { apikey, Authorization: `Bearer ${token}` } });
      const user = u.status === 200 ? await u.json() : null;
      if (!user?.id) checks.app_admin = `no: not a signed-in user (auth returned ${u.status})`;
      else {
        const a = await f(`${url}/rest/v1/app_admins?select=user_id&user_id=eq.${encodeURIComponent(user.id)}`, { headers: { apikey, Authorization: `Bearer ${token}` } });
        const rows = a.status === 200 ? await a.json() : null;
        if (Array.isArray(rows) && rows.length) return { ok: true, via: 'app_admin', checks: { ...checks, app_admin: `yes: ${user.email || user.id} is in app_admins` } };
        checks.app_admin = Array.isArray(rows) ? `no: ${user.email || user.id} is signed in but has no app_admins row` : `no: app_admins lookup returned ${a.status}`;
      }
    } catch (e) {
      checks.app_admin = `no: could not reach ${url} (${String((e as any)?.message || e)})`;
    }
  }
  return { ok: false, via: null, checks };
}

// ======================= index.ts =======================
// aspire-probe: discovery only. Authenticates to Aspire, reads a handful of records
// per endpoint, and returns a report on the shape of the data. It writes nothing,
// to Aspire or to Summit. client.ts holds the rules: GET only, call and time budgets.
//
// Three passes:
//   pass 3 (the default): reconcile Aspire against Summit. Every open opportunity plus
//          everything won in 180 days, by rep and status; and 90 days of activities per
//          person per week. See probe3.ts. Add "part": "ownership" or "activity" to run half.
//   pass 2: can site audits and client visits be counted, and who owns a deal? See probe2.ts.
//   pass 1: the core resources, pipeline and identifiers. See probe.ts.
// Pick one with a JSON body {"pass": 2} or ?pass=2. An empty body {} runs pass 3.
//
// Who may run it: see gate.ts. The service role key, a service_role JWT that
// Supabase confirms, or a Summit admin. Anyone else gets 403 with the result of
// each check. The Aspire credential never leaves this function.
//
// Deploy:  paste supabase/dashboard/aspire-probe.ts into the dashboard editor
//          or: supabase functions deploy aspire-probe --project-ref tyrtzxnhwjchtemytfxv
// Secrets: ASPIRE_CLIENT_ID, ASPIRE_CLIENT_SECRET (already set). Optional ASPIRE_BASE_URL.
//          Optional ASPIRE_PROBE_SECONDS: the time budget, default 125 (free plan cuts off at 150).
// Run:     POST or GET the function URL. Add ?format=text for the plain summary only, or
//          ?format=csv on pass 3 for the opportunity rows as a spreadsheet.


const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body, null, 2), { status, headers: { 'Content-Type': 'application/json' } });

async function readArgs(req: Request): Promise<{ pass: 1 | 2 | 3; part: Pass3Part }> {
  const u = new URL(req.url).searchParams;
  let body: any = {};
  try { body = (await req.clone().json()) || {}; } catch { /* empty or not JSON */ }
  const n = Number(u.get('pass') ?? body.pass);
  const pass = (n === 1 || n === 2 ? n : 3) as 1 | 2 | 3;
  const p = u.get('part') ?? body.part;
  return { pass, part: p === 'ownership' || p === 'activity' ? p : 'both' };
}

Deno.serve(async (req) => {
  const gate = await authorize(req.headers.get('Authorization'), {
    SUPABASE_URL: Deno.env.get('SUPABASE_URL'),
    SUPABASE_ANON_KEY: Deno.env.get('SUPABASE_ANON_KEY'),
    SUPABASE_SERVICE_ROLE_KEY: Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'),
  });
  if (!gate.ok) return json({ error: 'not allowed: none of the three checks passed', checks: gate.checks }, 403);

  const clientId = Deno.env.get('ASPIRE_CLIENT_ID');
  const secret = Deno.env.get('ASPIRE_CLIENT_SECRET');
  if (!clientId || !secret) return json({ error: 'ASPIRE_CLIENT_ID and ASPIRE_CLIENT_SECRET must both be set as function secrets', allowed_via: gate.via }, 500);

  const { pass, part } = await readArgs(req);
  const opts = { clientId, secret, base: Deno.env.get('ASPIRE_BASE_URL') || BASE };
  const secs = Number(Deno.env.get('ASPIRE_PROBE_SECONDS'));
  const report: any = pass === 1 ? await probe(opts) : pass === 2 ? await probe2(opts)
    : await probe3({ ...opts, part, deadlineMs: (Number.isFinite(secs) && secs > 0 ? secs : 125) * 1000 });

  const format = new URL(req.url).searchParams.get('format');
  if (format === 'csv' && pass === 3) {
    return new Response(toCsv(report.ownership?.rows || []), { headers: { 'Content-Type': 'text/csv; charset=utf-8', 'Content-Disposition': 'attachment; filename="aspire-opportunities.csv"' } });
  }
  if (format === 'text') {
    return new Response(`allowed via ${gate.via}, pass ${pass}${pass === 3 ? `, part ${part}` : ''}\n` + report.summary.join('\n') + '\n', { headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
  }
  return json({ allowed_via: gate.via, ...report });
});
