// GENERATED by scripts/bundle-probe.mjs from supabase/functions/aspire-probe. Do not edit by hand.
// Paste this whole file into the Supabase dashboard editor as the function "aspire-probe".

// ======================= probe.ts =======================
// Aspire discovery probe. Reads only. Reports the shape of the data, never copies it.
//
// Rules this file enforces:
// - Every data request is a GET. The only POST is the auth handshake, to a fixed list
//   of token paths. Anything else throws before it leaves the building.
// - A hard cap on total calls, spacing between calls, and backoff on 429.
// - No secret or token ever lands in the report. Sample records are reported as
//   field names and types, not values. Only the rep, branch and division fields
//   show example values, because that is the question being asked.

export const BASE = 'https://cloud-api.youraspire.com';

// the handshake candidates, tried in this order. OAuth client credentials first.
export const AUTH_ATTEMPTS = [
  { name: 'OAuth2 client_credentials (form body)', path: '/connect/token', kind: 'oauth' },
  { name: 'OAuth2 client_credentials (form body)', path: '/oauth/token', kind: 'oauth' },
  { name: 'OAuth2 client_credentials (form body)', path: '/token', kind: 'oauth' },
  { name: 'Aspire JSON handshake { ClientId, Secret }', path: '/Authorization', kind: 'aspire' },
];
const AUTH_PATHS = AUTH_ATTEMPTS.map((a) => a.path);

export const RESOURCES = [
  { name: 'Opportunities', paths: ['/Opportunities'] },
  { name: 'Properties', paths: ['/Properties'] },
  { name: 'Contracts', paths: ['/Contracts', '/ContractYears', '/Agreements'] },
  { name: 'Contacts', paths: ['/Contacts'] },
  { name: 'Invoices', paths: ['/Invoices'] },
  { name: 'Divisions', paths: ['/Divisions'] },
  // not asked for, but they answer question 4 and question 3
  { name: 'Branches', paths: ['/Branches'], extra: true },
  { name: 'OpportunityStatuses', paths: ['/OpportunityStatuses'], extra: true },
];

type Fetch = (url: string, init?: any) => Promise<any>;
export interface ProbeOptions {
  clientId: string;
  secret: string;
  base?: string;
  fetch?: Fetch;
  sleep?: (ms: number) => Promise<void>;
  now?: Date;
  maxCalls?: number;
  spacingMs?: number;
  deadlineMs?: number; // stop and report before the host kills the function
  clock?: () => number;
}

const DATE_RE = /^\d{4}-\d{2}-\d{2}([T ]\d{2}:\d{2}(:\d{2}(\.\d+)?)?(Z|[+-]\d{2}:?\d{2})?)?$/;
const isDate = (v: unknown) => typeof v === 'string' && DATE_RE.test(v);
const typeOf = (v: unknown) => (v === null || v === undefined ? 'null' : Array.isArray(v) ? 'array' : isDate(v) ? 'date' : typeof v);

function records(json: any): any[] | null {
  if (Array.isArray(json)) return json;
  if (json && Array.isArray(json.value)) return json.value;
  if (json && Array.isArray(json.Items)) return json.Items;
  if (json && Array.isArray(json.items)) return json.items;
  return null;
}
function envelope(json: any): string {
  if (Array.isArray(json)) return 'bare JSON array';
  if (json && Array.isArray(json.value)) return 'OData { value: [...] }';
  if (json && Array.isArray(json.Items)) return '{ Items: [...] }';
  if (json && Array.isArray(json.items)) return '{ items: [...] }';
  return 'unrecognized';
}
function fieldsOf(rec: any) {
  if (!rec || typeof rec !== 'object') return [];
  return Object.keys(rec).map((k) => ({ name: k, type: typeOf(rec[k]) }));
}
const qs = (o: Record<string, string>) => Object.entries(o).map(([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(v)}`).join('&');

export async function probe(opts: ProbeOptions) {
  const base = (opts.base || BASE).replace(/\/+$/, '');
  const f: Fetch = opts.fetch || ((u, i) => fetch(u, i));
  const sleep = opts.sleep || ((ms: number) => new Promise((r) => setTimeout(r, ms)));
  const now = opts.now || new Date();
  const maxCalls = opts.maxCalls ?? 70;
  const spacing = opts.spacingMs ?? 350;
  const deadline = opts.deadlineMs ?? 110_000; // edge functions are cut off at about 150s on the free plan
  const clock = opts.clock || (() => Date.now());
  const started = clock();
  const elapsed = () => clock() - started;
  let outOfTime = false;
  const log: any[] = [];
  const notes: string[] = [];
  let calls = 0;
  let throttled = 0;
  const resources: any = {};
  const samples: Record<string, any> = {};
  const open: any = { answer: 'unknown' };
  const ids: any = { rep: [], branch: [], division: [] };

  // ---------- the only door to the network ----------
  async function call(method: string, path: string, init: { headers?: any; body?: string } = {}) {
    const bare = path.split('?')[0];
    if (method !== 'GET' && !(method === 'POST' && AUTH_PATHS.includes(bare))) {
      throw new Error(`refused: ${method} ${bare}. The probe only reads.`);
    }
    for (let attempt = 0; attempt < 4; attempt++) {
      if (calls >= maxCalls || elapsed() > deadline) {
        const why = calls >= maxCalls ? 'call budget reached' : 'time budget reached';
        if (why === 'time budget reached') outOfTime = true;
        log.push({ method, path, skipped: why });
        return { status: 0, skipped: true, json: null, text: '', headers: {} as any };
      }
      calls++;
      if (calls > 1) await sleep(spacing);
      const t0 = Date.now();
      let res: any;
      try {
        res = await f(base + path, { method, headers: init.headers, body: init.body, signal: AbortSignal.timeout(20_000) });
      } catch (e) {
        log.push({ method, path, error: String((e as any)?.message || e) });
        return { status: -1, json: null, text: String(e), headers: {} as any };
      }
      const ms = Date.now() - t0;
      if (res.status === 429) {
        throttled++;
        const ra = Number(res.headers?.get?.('retry-after'));
        const wait = Number.isFinite(ra) && ra > 0 ? Math.min(ra, 60) * 1000 : 2000 * 2 ** attempt;
        if (elapsed() + wait > deadline) {
          outOfTime = true;
          log.push({ method, path, status: 429, ms, gave_up: 'waiting would run past the time budget' });
          return { status: 429, json: null, text: '', headers: {} as any };
        }
        log.push({ method, path, status: 429, ms, retry_in_ms: wait });
        await sleep(wait);
        continue;
      }
      const text = await res.text();
      let json: any = null;
      try { json = JSON.parse(text); } catch { /* not json */ }
      log.push({ method, path, status: res.status, ms });
      return { status: res.status, json, text, headers: res.headers };
    }
    log.push({ method, path, gave_up: 'still 429 after 4 tries' });
    return { status: 429, json: null, text: '', headers: {} as any };
  }

  // ---------- 1. auth ----------
  const auth: any = { worked: null, attempts: [] };
  let authHeader: string | null = null;
  for (const a of AUTH_ATTEMPTS) {
    const body = a.kind === 'oauth'
      ? qs({ grant_type: 'client_credentials', client_id: opts.clientId, client_secret: opts.secret })
      : JSON.stringify({ ClientId: opts.clientId, Secret: opts.secret });
    const headers = a.kind === 'oauth'
      ? { 'Content-Type': 'application/x-www-form-urlencoded', Accept: 'application/json' }
      : { 'Content-Type': 'application/json', Accept: 'application/json' };
    const r = await call('POST', a.path, { headers, body });
    const keys = r.json && typeof r.json === 'object' ? Object.keys(r.json) : [];
    const tokenKey = ['access_token', 'Token', 'token', 'AccessToken', 'accessToken'].find((k) => typeof r.json?.[k] === 'string');
    const attempt: any = { name: a.name, request: `POST ${a.path} (${headers['Content-Type']})`, status: r.status, response_fields: keys };
    auth.attempts.push(attempt);
    if (!(r.status >= 200 && r.status < 300) || !tokenKey) continue;

    const token = r.json[tokenKey];
    const scheme = typeof r.json.token_type === 'string' ? r.json.token_type : 'Bearer';
    // prove it: one cheap GET, first as "<scheme> <token>", then the raw token
    for (const h of [`${scheme} ${token}`, token]) {
      const v = await call('GET', `/Divisions?${qs({ $top: '1' })}`, { headers: { Authorization: h, Accept: 'application/json' } });
      if (v.status >= 200 && v.status < 300) { authHeader = h; attempt.verified_with = h === token ? 'Authorization: <raw token>' : `Authorization: ${scheme} <token>`; break; }
      attempt[`verify_${h === token ? 'raw' : 'scheme'}_status`] = v.status;
    }
    if (!authHeader) continue;
    const exp = r.json.expires_in ?? r.json.ExpiresIn ?? r.json.expiration ?? r.json.Expiration ?? null;
    auth.worked = {
      endpoint: `POST ${base}${a.path}`,
      body: a.kind === 'oauth' ? 'form: grant_type=client_credentials, client_id, client_secret' : 'JSON: { "ClientId": "...", "Secret": "..." }',
      token_field: tokenKey,
      header: attempt.verified_with,
      token_shape: token.split('.').length === 3 ? 'JWT (three dot-separated parts)' : `opaque string, ${token.length} chars`,
      expires: exp,
      refresh_token_returned: ['refresh_token', 'RefreshToken', 'refreshToken'].some((k) => typeof r.json[k] === 'string'),
    };
    break;
  }
  if (!authHeader) {
    notes.push('No auth handshake worked. Nothing past this point ran. Check the attempts list for the status each path returned.');
    return finish();
  }
  const H = { Authorization: authHeader, Accept: 'application/json' };
  const get = (p: string) => call('GET', p, { headers: H });

  // ---------- 2. each resource ----------
  for (const res of RESOURCES) {
    const out: any = { exists: false, path: null, tried: [] };
    resources[res.name] = out;
    let sample: any = null;
    for (const p of res.paths) {
      const r = await get(`${p}?${qs({ $top: '1' })}`);
      out.tried.push({ path: p, status: r.status });
      if (r.status === 401 || r.status === 403) { out.exists = 'probably, but this credential is not allowed to read it'; out.path = p; break; }
      if (r.status >= 200 && r.status < 300) {
        const recs = records(r.json);
        out.exists = true; out.path = p; out.envelope = envelope(r.json);
        if (recs === null) { out.note = 'responded, but not with a list of records'; break; }
        sample = recs[0] || null;
        out.honours_top = recs.length <= 1;
        out.fields = fieldsOf(sample);
        break;
      }
    }
    if (out.exists !== true || !out.path) continue;
    samples[res.name] = sample;

    // record count: OData $count, then /$count, else unknown
    const c = await get(`${out.path}?${qs({ $top: '0', $count: 'true' })}`);
    const odataCount = c.json && (c.json['@odata.count'] ?? c.json['odata.count'] ?? c.json.Count ?? c.json.count);
    if (c.status === 200 && Number.isFinite(Number(odataCount))) { out.count = Number(odataCount); out.count_method = '$count=true'; }
    else {
      const c2 = await get(`${out.path}/$count`);
      const n = Number(String(c2.text || '').trim());
      if (c2.status === 200 && Number.isFinite(n) && String(c2.text).trim() !== '') { out.count = n; out.count_method = '/$count'; }
      else { out.count = null; out.count_method = 'none worked. Counting would mean paging the whole set, which this probe will not do.'; }
    }

    // modified-since: find a modified-looking date field, then prove the filter is applied, not ignored
    const mf = out.fields?.find((x: any) => /modif|updat|changed|lastedit|edited/i.test(x.name) && (x.type === 'date' || x.type === 'null'));
    if (!sample) out.modified_since = { supported: 'unknown', why: 'no records to inspect' };
    else if (!mf) out.modified_since = { supported: 'unknown', why: 'no field on the sample record looks like a modified date', candidates: out.fields.filter((x: any) => x.type === 'date').map((x: any) => x.name) };
    else {
      const future = '2100-01-01T00:00:00Z';
      const since = new Date(now.getTime() - 30 * 86400000).toISOString().replace(/\.\d{3}Z$/, 'Z');
      const a = await get(`${out.path}?${qs({ $filter: `${mf.name} ge ${future}`, $top: '1' })}`);
      const ar = records(a.json);
      if (a.status !== 200 || ar === null) out.modified_since = { field: mf.name, supported: false, why: `$filter on ${mf.name} returned ${a.status}` };
      else if (ar.length > 0) out.modified_since = { field: mf.name, supported: false, why: `the filter was accepted but ignored: a year-2100 cutoff still returned records` };
      else {
        const b = await get(`${out.path}?${qs({ $filter: `${mf.name} ge ${since}`, $top: '0', $count: 'true' })}`);
        const n = b.json && Number(b.json['@odata.count']);
        out.modified_since = { field: mf.name, supported: true, syntax: `$filter=${mf.name} ge ${since}`, changed_last_30_days: Number.isFinite(n) ? n : 'not counted' };
      }
    }
  }

  // ---------- 3. open opportunities, or only sold work? ----------
  const opp = resources.Opportunities;
  if (opp?.exists === true && samples.Opportunities) {
    const keys = Object.keys(samples.Opportunities);
    const pickKey = (re: RegExp) => keys.find((k) => re.test(k)) || null;
    const statusKey = pickKey(/^(opportunity)?status(name)?$/i) || pickKey(/status.*name/i) || pickKey(/status/i);
    const wonKey = pickKey(/won.?date/i);
    const lostKey = pickKey(/lost.?date/i);
    const stageKey = pickKey(/stage/i);
    const typeKey = pickKey(/^(opportunity)?type(name)?$/i);
    open.fields = { status: statusKey, won_date: wonKey, lost_date: lostKey, stage: stageKey, type: typeKey };

    const sel = [statusKey, stageKey, typeKey, wonKey, lostKey, opp.modified_since?.field].filter(Boolean).join(',');
    const order = opp.modified_since?.field ? { $orderby: `${opp.modified_since.field} desc` } : {};
    let r = await get(`/Opportunities?${qs({ $top: '500', ...(sel ? { $select: sel } : {}), ...order })}`);
    if (r.status !== 200 || !records(r.json)) r = await get(`/Opportunities?${qs({ $top: '200' })}`);
    const recs = records(r.json) || [];
    const tally = (k: string | null) => { const t: Record<string, number> = {}; if (!k) return t; for (const x of recs) { const v = x[k] === null || x[k] === undefined ? '(blank)' : String(x[k]); t[v] = (t[v] || 0) + 1; } return t; };
    open.sampled = recs.length;
    open.by_status = tally(statusKey);
    if (stageKey) open.by_stage = tally(stageKey);
    if (typeKey) open.by_type = tally(typeKey);
    const closed = /won|sold|lost|closed|cancel|complete|declin|dead|void/i;
    const openByStatus = statusKey ? recs.filter((x) => x[statusKey] && !closed.test(String(x[statusKey]))).length : null;
    const openByDates = wonKey && lostKey ? recs.filter((x) => !x[wonKey] && !x[lostKey]).length : null;
    open.open_in_sample_by_status = openByStatus;
    open.open_in_sample_by_dates = openByDates;

    // exact total, if the dates filter works
    if (wonKey && lostKey) {
      const e = await get(`/Opportunities?${qs({ $filter: `${wonKey} eq null and ${lostKey} eq null`, $top: '0', $count: 'true' })}`);
      const n = e.json && Number(e.json['@odata.count']);
      if (e.status === 200 && Number.isFinite(n)) open.total_open_by_dates = n;
    }
    if (resources.OpportunityStatuses?.exists === true) {
      const s = await get(`/OpportunityStatuses?${qs({ $top: '100' })}`);
      const sr = records(s.json) || [];
      const nameKey = sr[0] && Object.keys(sr[0]).find((k) => /name/i.test(k));
      open.status_list = nameKey ? sr.map((x) => x[nameKey]) : sr.length ? 'returned, no name field' : [];
    }
    const openCount = Math.max(openByStatus ?? 0, openByDates ?? 0, open.total_open_by_dates ?? 0);
    open.answer = openCount > 0
      ? `yes. open opportunities are in there (${openCount} found by ${openByDates ? 'blank won and lost dates' : 'status'}${open.total_open_by_dates !== undefined ? `, ${open.total_open_by_dates} total by the dates filter` : ''})`
      : recs.length ? 'no open ones in the sample. Only sold or lost work came back. See by_status.' : 'no opportunities came back';
  }

  // ---------- 4. who is the rep, what is the branch ----------
  if (samples.Opportunities) {
    const keys = Object.keys(samples.Opportunities);
    const r = await get(`/Opportunities?${qs({ $top: '50' })}`);
    const recs = records(r.json) || [samples.Opportunities];
    const describe = (k: string) => {
      const vals = recs.map((x) => x[k]).filter((v) => v !== null && v !== undefined && v !== '');
      return { field: k, type: typeOf(recs.find((x) => x[k] != null)?.[k]), filled: `${vals.length} of ${recs.length}`, distinct: new Set(vals.map(String)).size, examples: [...new Set(vals.map(String))].slice(0, 3) };
    };
    ids.rep = keys.filter((k) => /sales.?rep|salesperson|sales.?person|estimator|account.?manager|owner|assigned|^rep|employee|user(id|name)?$/i.test(k)).map(describe);
    ids.branch = keys.filter((k) => /branch|office|region|location/i.test(k)).map(describe);
    ids.division = keys.filter((k) => /division/i.test(k)).map(describe);
    ids.other_person_fields = keys.filter((k) => /contact|manager/i.test(k) && !ids.rep.some((x: any) => x.field === k)).slice(0, 12);
  }
  for (const name of ['Divisions', 'Branches']) {
    const s = samples[name];
    if (!s) continue;
    const r = await get(`${resources[name].path}?${qs({ $top: '50' })}`);
    const recs = records(r.json) || [];
    const idKey = Object.keys(s).find((k) => /id$/i.test(k));
    const nameKey = Object.keys(s).find((k) => /name/i.test(k));
    ids[`${name.toLowerCase()}_list`] = recs.map((x) => ({ id: idKey ? x[idKey] : undefined, name: nameKey ? x[nameKey] : undefined }));
  }

  return finish();

  function finish() {
    const summary: string[] = [];
    if (auth.worked) summary.push(`Auth: ${auth.worked.endpoint} with ${auth.worked.body}. Token in "${auth.worked.token_field}", sent as ${auth.worked.header}.`);
    else summary.push('Auth: nothing worked. See auth.attempts.');
    for (const [n, r] of Object.entries<any>(resources || {})) {
      if (r.exists === true) summary.push(`${n}: ${r.path}, ${r.count ?? 'count unknown'} records, ${r.fields?.length ?? 0} fields, modified-since ${r.modified_since?.supported === true ? `yes (${r.modified_since.field})` : r.modified_since?.supported === false ? 'no' : 'unknown'}.`);
      else summary.push(`${n}: ${r.exists || 'not found'} (tried ${r.tried.map((t: any) => `${t.path} ${t.status}`).join(', ')}).`);
    }
    if (open.answer) summary.push(`Open opportunities: ${open.answer}.`);
    if (ids.rep?.length) summary.push(`Rep on an opportunity: ${ids.rep.map((x: any) => x.field).join(', ')}.`);
    if (ids.branch?.length || ids.division?.length) summary.push(`Branch or division: ${[...(ids.branch || []), ...(ids.division || [])].map((x: any) => x.field).join(', ')}.`);
    if (throttled) summary.push(`Throttled ${throttled} time(s). Backed off and retried.`);
    if (outOfTime) summary.push('Stopped early to stay inside the time budget. Everything above is real; anything missing was skipped, not failed. Run it again to fill the gaps.');
    return {
      generated_at: now.toISOString(), base, calls_used: calls, call_budget: maxCalls, throttled,
      seconds: Math.round(elapsed() / 1000), stopped_early: outOfTime,
      // enforced by call(): anything but GET, or POST to a token path, throws before it is sent
      data_writes: 0,
      summary, auth, resources: resources || {}, open_opportunities: open, identifiers: ids, notes, log,
    };
  }
}

// ======================= gate.ts =======================
// Who may run the probe. Three ways in, checked in order:
//   1. the bearer token equals SUPABASE_SERVICE_ROLE_KEY
//   2. the bearer token is a JWT with role "service_role", and Supabase itself
//      accepts it on an admin-only endpoint (so a hand-made token with that
//      claim but no valid signature is refused)
//   3. the bearer token belongs to a signed-in user with a row in app_admins
// Everyone else is refused, with the result of every check, so a failure says why.
// Never echoes a key or a token. Only its kind and length.

type Fetch = (url: string, init?: any) => Promise<any>;
export interface GateEnv {
  SUPABASE_URL?: string;
  SUPABASE_ANON_KEY?: string;
  SUPABASE_SERVICE_ROLE_KEY?: string;
}

export function kindOf(t: string | undefined | null) {
  if (!t) return 'not set';
  if (t.startsWith('sb_secret_')) return `new-format secret key (sb_secret_..., ${t.length} chars)`;
  if (t.startsWith('sb_publishable_')) return `new-format publishable key (sb_publishable_..., ${t.length} chars)`;
  if (t.split('.').length === 3) return `JWT (${t.length} chars)`;
  return `opaque string (${t.length} chars)`;
}

export function jwtClaims(t: string): any | null {
  const parts = t.split('.');
  if (parts.length !== 3) return null;
  try {
    const b64 = parts[1].replace(/-/g, '+').replace(/_/g, '/').padEnd(Math.ceil(parts[1].length / 4) * 4, '=');
    return JSON.parse(atob(b64));
  } catch {
    return null;
  }
}

export async function authorize(authHeader: string | null, env: GateEnv, f: Fetch = (u, i) => fetch(u, i)) {
  const checks: Record<string, string> = {};
  const token = (authHeader || '').replace(/^Bearer\s+/i, '').trim();
  const url = (env.SUPABASE_URL || '').replace(/\/+$/, '');
  if (!token) {
    return { ok: false, via: null, checks: { header: 'no: no Authorization: Bearer <token> header on the request' } };
  }
  checks.token = `received a ${kindOf(token)}`;

  // 1. exact match to the injected service role key
  const svc = env.SUPABASE_SERVICE_ROLE_KEY;
  if (!svc) checks.service_key_match = 'no: SUPABASE_SERVICE_ROLE_KEY is not set in this function';
  else if (token === svc) return { ok: true, via: 'service_key_match', checks: { ...checks, service_key_match: 'yes' } };
  else checks.service_key_match = `no: token differs from SUPABASE_SERVICE_ROLE_KEY, which is a ${kindOf(svc)}`;

  // 2. a JWT that claims service_role, confirmed by Supabase
  const claims = jwtClaims(token);
  if (!claims) checks.service_role_jwt = 'no: token is not a JWT';
  else if (claims.role !== 'service_role') checks.service_role_jwt = `no: JWT role claim is "${claims.role ?? '(none)'}"`;
  else if (!url) checks.service_role_jwt = 'no: role claim is service_role, but SUPABASE_URL is not set, so it could not be confirmed';
  else {
    try {
      const r = await f(`${url}/auth/v1/admin/users?page=1&per_page=1`, { headers: { apikey: token, Authorization: `Bearer ${token}` } });
      if (r.status === 200) return { ok: true, via: 'service_role_jwt', checks: { ...checks, service_role_jwt: 'yes: role claim is service_role and Supabase accepted it' } };
      checks.service_role_jwt = `no: role claim is service_role but Supabase rejected the token (${r.status}). Wrong project, rotated, or not a real key.`;
    } catch (e) {
      checks.service_role_jwt = `no: could not reach ${url} to confirm it (${String((e as any)?.message || e)})`;
    }
  }

  // 3. a signed-in Summit admin
  if (!url) checks.app_admin = 'no: SUPABASE_URL is not set';
  else if (claims && claims.role === 'service_role') checks.app_admin = 'no: token is a service role key, not a user';
  else {
    const apikey = env.SUPABASE_ANON_KEY || token;
    try {
      const u = await f(`${url}/auth/v1/user`, { headers: { apikey, Authorization: `Bearer ${token}` } });
      const user = u.status === 200 ? await u.json() : null;
      if (!user?.id) checks.app_admin = `no: not a signed-in user (auth returned ${u.status})`;
      else {
        const a = await f(`${url}/rest/v1/app_admins?select=user_id&user_id=eq.${encodeURIComponent(user.id)}`, { headers: { apikey, Authorization: `Bearer ${token}` } });
        const rows = a.status === 200 ? await a.json() : null;
        if (Array.isArray(rows) && rows.length) return { ok: true, via: 'app_admin', checks: { ...checks, app_admin: `yes: ${user.email || user.id} is in app_admins` } };
        checks.app_admin = Array.isArray(rows) ? `no: ${user.email || user.id} is signed in but has no app_admins row` : `no: app_admins lookup returned ${a.status}`;
      }
    } catch (e) {
      checks.app_admin = `no: could not reach ${url} (${String((e as any)?.message || e)})`;
    }
  }
  return { ok: false, via: null, checks };
}

// ======================= index.ts =======================
// aspire-probe: discovery only. Authenticates to Aspire, reads a handful of records
// per endpoint, and returns a report on the shape of the data. It writes nothing,
// to Aspire or to Summit. See probe.ts for the rules it enforces.
//
// Who may run it: see gate.ts. The service role key, a service_role JWT that
// Supabase confirms, or a Summit admin. Anyone else gets 403 with the result of
// each check. The Aspire credential never leaves this function.
//
// Deploy:  supabase functions deploy aspire-probe --project-ref tyrtzxnhwjchtemytfxv
//          or paste supabase/dashboard/aspire-probe.ts into the dashboard editor
// Secrets: ASPIRE_CLIENT_ID, ASPIRE_CLIENT_SECRET (already set). Optional ASPIRE_BASE_URL.
// Run:     POST or GET the function URL. Add ?format=text for the plain summary only.


const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body, null, 2), { status, headers: { 'Content-Type': 'application/json' } });

Deno.serve(async (req) => {
  const gate = await authorize(req.headers.get('Authorization'), {
    SUPABASE_URL: Deno.env.get('SUPABASE_URL'),
    SUPABASE_ANON_KEY: Deno.env.get('SUPABASE_ANON_KEY'),
    SUPABASE_SERVICE_ROLE_KEY: Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'),
  });
  if (!gate.ok) return json({ error: 'not allowed: none of the three checks passed', checks: gate.checks }, 403);

  const clientId = Deno.env.get('ASPIRE_CLIENT_ID');
  const secret = Deno.env.get('ASPIRE_CLIENT_SECRET');
  if (!clientId || !secret) return json({ error: 'ASPIRE_CLIENT_ID and ASPIRE_CLIENT_SECRET must both be set as function secrets', allowed_via: gate.via }, 500);

  const report = await probe({ clientId, secret, base: Deno.env.get('ASPIRE_BASE_URL') || BASE });

  if (new URL(req.url).searchParams.get('format') === 'text') {
    return new Response(`allowed via ${gate.via}\n` + report.summary.join('\n') + '\n', { headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
  }
  return json({ allowed_via: gate.via, ...report });
});
