// GENERATED by scripts/bundle-probe.mjs from supabase/functions/source-sync. Do not edit by hand.
// Paste this whole file into the Supabase dashboard editor as the function "source-sync".

// ======================= gate.ts =======================
// Who may run the probe. Three ways in, checked in order:
//   1. the bearer token equals SUPABASE_SERVICE_ROLE_KEY
//   2. the bearer token is a JWT with role "service_role", and Supabase itself
//      accepts it on an admin-only endpoint (so a hand-made token with that
//      claim but no valid signature is refused)
//   3. the bearer token belongs to a signed-in user with a row in app_admins
// Everyone else is refused, with the result of every check, so a failure says why.
// Never echoes a key or a token. Only its kind and length.

type GateFetch = (url: string, init?: any) => Promise<any>;
export interface GateEnv {
  SUPABASE_URL?: string;
  SUPABASE_ANON_KEY?: string;
  SUPABASE_SERVICE_ROLE_KEY?: string;
}

export function kindOf(t: string | undefined | null) {
  if (!t) return 'not set';
  if (t.startsWith('sb_secret_')) return `new-format secret key (sb_secret_..., ${t.length} chars)`;
  if (t.startsWith('sb_publishable_')) return `new-format publishable key (sb_publishable_..., ${t.length} chars)`;
  if (t.split('.').length === 3) return `JWT (${t.length} chars)`;
  return `opaque string (${t.length} chars)`;
}

export function jwtClaims(t: string): any | null {
  const parts = t.split('.');
  if (parts.length !== 3) return null;
  try {
    const b64 = parts[1].replace(/-/g, '+').replace(/_/g, '/').padEnd(Math.ceil(parts[1].length / 4) * 4, '=');
    return JSON.parse(atob(b64));
  } catch {
    return null;
  }
}

export async function authorize(authHeader: string | null, env: GateEnv, f: GateFetch = (u, i) => fetch(u, i)) {
  const checks: Record<string, string> = {};
  const token = (authHeader || '').replace(/^Bearer\s+/i, '').trim();
  const url = (env.SUPABASE_URL || '').replace(/\/+$/, '');
  if (!token) {
    return { ok: false, via: null, checks: { header: 'no: no Authorization: Bearer <token> header on the request' } };
  }
  checks.token = `received a ${kindOf(token)}`;

  // 1. exact match to the injected service role key
  const svc = env.SUPABASE_SERVICE_ROLE_KEY;
  if (!svc) checks.service_key_match = 'no: SUPABASE_SERVICE_ROLE_KEY is not set in this function';
  else if (token === svc) return { ok: true, via: 'service_key_match', checks: { ...checks, service_key_match: 'yes' } };
  else checks.service_key_match = `no: token differs from SUPABASE_SERVICE_ROLE_KEY, which is a ${kindOf(svc)}`;

  // 2. a JWT that claims service_role, confirmed by Supabase
  const claims = jwtClaims(token);
  if (!claims) checks.service_role_jwt = 'no: token is not a JWT';
  else if (claims.role !== 'service_role') checks.service_role_jwt = `no: JWT role claim is "${claims.role ?? '(none)'}"`;
  else if (!url) checks.service_role_jwt = 'no: role claim is service_role, but SUPABASE_URL is not set, so it could not be confirmed';
  else {
    try {
      const r = await f(`${url}/auth/v1/admin/users?page=1&per_page=1`, { headers: { apikey: token, Authorization: `Bearer ${token}` } });
      if (r.status === 200) return { ok: true, via: 'service_role_jwt', checks: { ...checks, service_role_jwt: 'yes: role claim is service_role and Supabase accepted it' } };
      checks.service_role_jwt = `no: role claim is service_role but Supabase rejected the token (${r.status}). Wrong project, rotated, or not a real key.`;
    } catch (e) {
      checks.service_role_jwt = `no: could not reach ${url} to confirm it (${String((e as any)?.message || e)})`;
    }
  }

  // 3. a signed-in Summit admin
  if (!url) checks.app_admin = 'no: SUPABASE_URL is not set';
  else if (claims && claims.role === 'service_role') checks.app_admin = 'no: token is a service role key, not a user';
  else {
    const apikey = env.SUPABASE_ANON_KEY || token;
    try {
      const u = await f(`${url}/auth/v1/user`, { headers: { apikey, Authorization: `Bearer ${token}` } });
      const user = u.status === 200 ? await u.json() : null;
      if (!user?.id) checks.app_admin = `no: not a signed-in user (auth returned ${u.status})`;
      else {
        const a = await f(`${url}/rest/v1/app_admins?select=user_id&user_id=eq.${encodeURIComponent(user.id)}`, { headers: { apikey, Authorization: `Bearer ${token}` } });
        const rows = a.status === 200 ? await a.json() : null;
        if (Array.isArray(rows) && rows.length) return { ok: true, via: 'app_admin', checks: { ...checks, app_admin: `yes: ${user.email || user.id} is in app_admins` } };
        checks.app_admin = Array.isArray(rows) ? `no: ${user.email || user.id} is signed in but has no app_admins row` : `no: app_admins lookup returned ${a.status}`;
      }
    } catch (e) {
      checks.app_admin = `no: could not reach ${url} (${String((e as any)?.message || e)})`;
    }
  }
  return { ok: false, via: null, checks };
}

// ======================= aspire.ts =======================
// The only door to Aspire for the sync. Read only.
//
// - Every request to Aspire is a GET. The one exception is the login, POST /Authorization.
//   Anything else throws before it is sent. The credential is GET only too, so a write would
//   fail at Aspire anyway. This makes sure one is never tried.
// - 350ms between calls, backoff on 429, a 20s timeout per call, and a time budget.
// - A 401 mid-run logs in again, once.
// - No secret or token ever lands in a log, an error or the result.

export const ASPIRE_BASE = 'https://cloud-api.youraspire.com';
export const AUTH_PATH = '/Authorization';

type Fetch = (url: string, init?: any) => Promise<any>;
export interface AspireOptions {
  clientId: string;
  secret: string;
  base?: string;
  fetch?: Fetch;
  sleep?: (ms: number) => Promise<void>;
  spacingMs?: number;
  deadlineMs?: number;
  clock?: () => number;
}

export const toQuery = (o: Record<string, string>) => Object.entries(o).map(([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(v)}`).join('&');
export function recordsOf(json: any): any[] | null {
  if (Array.isArray(json)) return json;
  if (json && Array.isArray(json.value)) return json.value;
  return null;
}

export function aspireClient(opts: AspireOptions) {
  const base = (opts.base || ASPIRE_BASE).replace(/\/+$/, '');
  const f: Fetch = opts.fetch || ((u, i) => fetch(u, i));
  const sleep = opts.sleep || ((ms: number) => new Promise((r) => setTimeout(r, ms)));
  const spacing = opts.spacingMs ?? 350;
  const deadline = opts.deadlineMs ?? 120_000;
  const clock = opts.clock || (() => Date.now());
  const started = clock();
  const s = { calls: 0, throttled: 0, relogins: 0, outOfTime: false };
  let token: string | null = null;

  async function send(method: string, path: string, init: { headers?: any; body?: string } = {}) {
    const bare = path.split('?')[0];
    if (method !== 'GET' && !(method === 'POST' && bare === AUTH_PATH)) {
      throw new Error(`refused: ${method} ${bare}. The sync never writes to Aspire.`);
    }
    for (let attempt = 0; attempt < 5; attempt++) {
      if (clock() - started > deadline) { s.outOfTime = true; return { status: 0, skipped: true, json: null }; }
      if (s.calls++) await sleep(spacing);
      let res: any;
      try {
        res = await f(base + path, { method, headers: init.headers, body: init.body, signal: AbortSignal.timeout(20_000) });
      } catch (e) {
        return { status: -1, json: null, error: String((e as any)?.message || e) };
      }
      if (res.status === 429) {
        s.throttled++;
        const ra = Number(res.headers?.get?.('retry-after'));
        const wait = Number.isFinite(ra) && ra > 0 ? Math.min(ra, 60) * 1000 : 2000 * 2 ** attempt;
        if (clock() - started + wait > deadline) { s.outOfTime = true; return { status: 429, json: null }; }
        await sleep(wait);
        continue;
      }
      const text = await res.text();
      let json: any = null;
      try { json = JSON.parse(text); } catch { /* not json */ }
      return { status: res.status, json };
    }
    return { status: 429, json: null };
  }

  async function login() {
    const r = await send('POST', AUTH_PATH, {
      headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
      body: JSON.stringify({ ClientId: opts.clientId, Secret: opts.secret }),
    });
    if (r.skipped) throw new Error('ran out of time before logging in to Aspire');
    if (r.status !== 200 || typeof r.json?.Token !== 'string') throw new Error(`Aspire login failed (${r.status})`);
    token = r.json.Token;
  }

  async function get(path: string) {
    if (!token) await login();
    let r = await send('GET', path, { headers: { Authorization: `Bearer ${token}`, Accept: 'application/json' } });
    if (r.status === 401 && !s.relogins) {
      s.relogins++;
      await login();
      r = await send('GET', path, { headers: { Authorization: `Bearer ${token}`, Accept: 'application/json' } });
    }
    return r;
  }

  return { get, stats: () => ({ ...s, seconds: Math.round((clock() - started) / 1000) }) };
}

// ======================= sync.ts =======================
// The sync, for any connected source. The run itself is generic: resolve the source, begin a run, hand the
// connector a writer, finish the run (migration 012: source_sync_resolve, _begin, _upsert, _finish). Those only
// write deals and source_runs. Commits, goals and the book are never touched. Mapping a source's fields into
// Summit's is config in deal_sources.mapping; a connector only fetches.
//
// The Aspire connector: Opportunities. Full pull on the first run, then ModifiedDate since the last good run. Pages by key:
// OpportunityID gt <last seen>, ordered by OpportunityID asc, $top=200 (pageSize). $count does not work at
// Aspire, so a pull ends on an empty page or a short one. Each page is written as it arrives, so
// a run that runs out of time keeps what it got, is logged as partial, and does not move the
// watermark. The next run picks it up. A page Summit fails to write is logged and skipped; the
// run carries on, ends partial, and the next run pulls those rows again.


export interface Db { rpc: (fn: string, args: Record<string, unknown>) => Promise<any> }

// Summit's side: PostgREST RPC with the service role key. Only these functions are called.
export const SYNC_RPCS = ['source_sync_resolve', 'source_sync_begin', 'source_sync_upsert', 'source_sync_finish'];
export function restDb(url: string, key: string, f: (u: string, i?: any) => Promise<any> = (u, i) => fetch(u, i)): Db {
  const base = url.replace(/\/+$/, '');
  return {
    async rpc(fn, args) {
      if (!SYNC_RPCS.includes(fn)) throw new Error(`refused: ${fn} is not a sync function`);
      const res = await f(`${base}/rest/v1/rpc/${fn}`, {
        method: 'POST',
        headers: { apikey: key, Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' },
        body: JSON.stringify(args),
      });
      const text = await res.text();
      let json: any = null;
      try { json = JSON.parse(text); } catch { /* not json */ }
      if (res.status >= 300) throw new Error(`${fn}: ${json?.message || text.slice(0, 200) || res.status}`);
      return json;
    },
  };
}

// what a connector gets: where the run starts, and a writer for pages of raw records
export interface ConnectorRun {
  begin: { run_id: number; mode: string; since: string | null; options?: Record<string, unknown> };
  credentials: Record<string, string>;
  write: (records: any[], label?: string) => Promise<void>;  // label: which records, for the log
  pageSize: number;
  maxPages: number;
}
export interface ConnectorResult {
  complete: boolean;   // the source said it has nothing more. Only then can a full pull mark rows removed
  errors: string[];    // the run stopped
  pageErrors: string[];
  notes: string[];
  calls: number;
  seconds?: number;
}
export type Connector = (r: ConnectorRun) => Promise<ConnectorResult>;

export interface SyncArgs {
  db: Db;
  connectors: Record<string, Connector>;
  credentials: (ref: string | null) => Record<string, string> | { error: string };
  source?: number | null;
  workspace?: string | null;
  full?: boolean;
  trigger?: string;
  pageSize?: number; // 1 to 1000
  maxPages?: number;
}

export async function runSync(a: SyncArgs) {
  const pageSize = Math.min(1000, Math.max(1, Math.floor(Number(a.pageSize) || 200)));
  const maxPages = a.maxPages ?? 200;
  let sourceId = a.source ?? null;
  if (!sourceId) {
    let r: any;
    try { r = await a.db.rpc('source_sync_resolve', { p_slug: a.workspace ?? null }); } catch (e) {
      return { status: 'error', error: `could not find the source in Summit: ${String((e as any)?.message || e)}` };
    }
    if (!r || r.error) return { status: 'refused', error: r?.error || 'source_sync_resolve returned nothing' };
    sourceId = r.source_id;
  }
  let begin: any;
  try {
    begin = await a.db.rpc('source_sync_begin', { p_source: sourceId, p_trigger: a.trigger || 'manual', p_full: !!a.full });
  } catch (e) {
    return { status: 'error', error: `could not start a run in Summit: ${String((e as any)?.message || e)}` };
  }
  if (!begin || begin.error) return { status: 'refused', error: begin?.error || 'source_sync_begin returned nothing' };

  const finish = async (status: string, res: Partial<ConnectorResult>) => {
    const allErrors = [...(res.pageErrors || []), ...(res.errors || [])];
    try {
      const run = await a.db.rpc('source_sync_finish', {
        p_run: begin.run_id, p_status: status, p_calls: res.calls || 0, p_errors: allErrors, p_notes: res.notes || [], p_complete: status === 'ok',
      });
      return { status, seconds: res.seconds, run };
    } catch (e) {
      // the run stays "running" in the log; the next run closes it out after 15 minutes
      return { status: 'error', seconds: res.seconds, run_id: begin.run_id, errors: [...allErrors, `could not log the end of the run: ${String((e as any)?.message || e)}`] };
    }
  };

  const connector = a.connectors[begin.connector];
  if (!connector) return finish('error', { errors: [`no connector called ${begin.connector} is built`] });
  const creds = a.credentials(begin.credential_ref ?? null);
  if ('error' in creds) return finish('error', { errors: [String(creds.error)] });

  const writes: string[] = [];
  const pageErrors: string[] = [];
  let pageNo = 0;
  const write = async (records: any[], label?: string) => {
    pageNo++;
    const t0 = Date.now();
    try {
      await a.db.rpc('source_sync_upsert', { p_run: begin.run_id, p_rows: records });
      writes.push(`${((Date.now() - t0) / 1000).toFixed(1)}s`);
    } catch (e) {
      pageErrors.push(`page ${pageNo} (${label ? `${label}, ` : ''}${records.length} rows) was not saved: ${String((e as any)?.message || e)}`);
      writes.push('failed');
    }
  };
  let res: ConnectorResult;
  try {
    res = await connector({ begin, credentials: creds, write, pageSize, maxPages });
  } catch (e) {
    res = { complete: false, errors: [String((e as any)?.message || e)], pageErrors: [], notes: [], calls: 0 };
  }
  res.pageErrors = [...pageErrors, ...(res.pageErrors || [])];
  if (writes.length) res.notes.push(`time to save each page: ${writes.join(', ')}`);
  // a failed page means rows are missing: partial, so the cutoff stays put and nothing is marked removed
  const status = res.errors.length ? 'error' : res.complete && !res.pageErrors.length ? 'ok' : 'partial';
  return finish(status, res);
}

// ---------------------------------------------------------------------------------------------------
// The Aspire connector. GET only. Pages Opportunities by OpportunityID.
export function aspireConnector(opts: Omit<AspireOptions, 'clientId' | 'secret'> = {}): Connector {
  return async ({ begin, credentials, write, pageSize, maxPages }) => {
    const aspire = aspireClient({ ...opts, clientId: credentials.CLIENT_ID, secret: credentials.CLIENT_SECRET, base: opts.base || credentials.BASE_URL || undefined });
    const errors: string[] = [];
    const notes: string[] = [];
    let complete = false;
    try {
      const since = begin.mode === 'incremental' && begin.since ? `${begin.since}Z` : null;
      if (since) notes.push(`incremental: ModifiedDate ge ${since}`);
      else notes.push('full pull');
      notes.push(`pages of ${pageSize}`);
      let last: number | null = null;
      let largest = 0;
      for (let page = 1; page <= maxPages; page++) {
        const filter = [since && `ModifiedDate ge ${since}`, last !== null && `OpportunityID gt ${last}`].filter(Boolean).join(' and ');
        const q: Record<string, string> = { $top: String(pageSize), $orderby: 'OpportunityID asc' };
        if (filter) q.$filter = filter;
        const r = await aspire.get(`/Opportunities?${toQuery(q)}`);
        if (r.skipped) { notes.push(`stopped at page ${page} to stay inside the time budget. The next run picks up the rest`); break; }
        const recs = recordsOf(r.json);
        if (r.status !== 200 || !recs) { errors.push(`page ${page}: Aspire returned ${r.status}${r.error ? ` (${r.error})` : ''}`); break; }
        if (!recs.length) { complete = true; break; }
        const ids = recs.map((x) => Number(x?.OpportunityID));
        if (ids.some((n) => !Number.isFinite(n))) { errors.push(`page ${page}: a record has no OpportunityID`); break; }
        if (ids.some((n, i) => (i ? n <= ids[i - 1] : last !== null && n <= last))) {
          errors.push(`page ${page}: Aspire ignored the OpportunityID order or the gt filter. Stopped so nothing is counted twice`);
          break;
        }
        await write(recs, `OpportunityID ${ids[0]} to ${ids[ids.length - 1]}`);
        last = ids[ids.length - 1];
        largest = Math.max(largest, recs.length);
        if (page > 1 && recs.length < largest) { complete = true; break; } // a short page after a full one is the last
        if (page === maxPages) notes.push(`stopped at the ${maxPages}-page safety cap`);
      }
    } catch (e) {
      errors.push(String((e as any)?.message || e));
    }
    const st = aspire.stats();
    if (st.throttled) notes.push(`throttled ${st.throttled} time(s), backed off and retried`);
    if (st.relogins) notes.push('the Aspire token expired mid-run, logged in again');
    return { complete, errors, pageErrors: [], notes, calls: st.calls, seconds: st.seconds };
  };
}

// credentials by reference: env:ASPIRE reads ASPIRE_CLIENT_ID, ASPIRE_CLIENT_SECRET and ASPIRE_BASE_URL from the function's
// secrets, returned without the prefix. Nothing else is supported yet, and nothing is ever read from the deal_sources row itself.
export function envCredentials(env: (k: string) => string | undefined) {
  return (ref: string | null): Record<string, string> | { error: string } => {
    const m = /^env:([A-Z][A-Z0-9_]*)$/.exec(ref || '');
    if (!m) return { error: `credential reference ${ref || '(none)'} is not supported. Use env:<PREFIX>` };
    const out: Record<string, string> = {};
    for (const k of ['CLIENT_ID', 'CLIENT_SECRET', 'BASE_URL', 'API_KEY']) { const v = env(`${m[1]}_${k}`); if (v) out[k] = v; }
    if (!Object.keys(out).length) return { error: `no secrets named ${m[1]}_* are set on the function` };
    return out;
  };
}

// ======================= index.ts =======================
// source-sync: a connected source into Summit's deals. Reads the source, never writes to it.
// Writes only deals, deal_snapshots and source_runs, through the SQL functions in migration 012.
//
// Who may run it: the same gate as aspire-probe. The service role key (what the nightly pg_cron
// job sends), a service_role JWT that Supabase confirms, or a Summit admin. Anyone else gets 403.
//
// Body (all optional):
//   {"source": 3}            the deal_sources id. Without it: {"workspace": "<slug>"}, else the only connected source
//   {"full": true}           re-pull everything instead of changes since the last good run
//   {"trigger": "cron"}      a label for the log
//   {"pageSize": 200}        records per page and per write to Summit. Default 200, max 1000
//
// Connectors built: aspire. Credentials come by reference (deal_sources.credential_ref), never stored in Summit:
//   env:ASPIRE  ->  ASPIRE_CLIENT_ID, ASPIRE_CLIENT_SECRET (already set), optional ASPIRE_BASE_URL.
// Optional SYNC_SECONDS (time budget, default 120. The free plan cuts off at 150).
//
// Deploy:  paste supabase/dashboard/source-sync.ts into the dashboard editor as "source-sync"
//          or: supabase functions deploy source-sync --project-ref tyrtzxnhwjchtemytfxv


const reply = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body, null, 2), { status, headers: { 'Content-Type': 'application/json' } });

Deno.serve(async (req) => {
  const env = (k: string) => Deno.env.get(k);
  const gate = await authorize(req.headers.get('Authorization'), {
    SUPABASE_URL: env('SUPABASE_URL'), SUPABASE_ANON_KEY: env('SUPABASE_ANON_KEY'), SUPABASE_SERVICE_ROLE_KEY: env('SUPABASE_SERVICE_ROLE_KEY'),
  });
  if (!gate.ok) return reply({ error: 'not allowed: none of the three checks passed', checks: gate.checks }, 403);

  const url = env('SUPABASE_URL'), key = env('SUPABASE_SERVICE_ROLE_KEY');
  if (!url || !key) return reply({ error: 'SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are not available to this function' }, 500);

  let body: any = {};
  try { body = (await req.json()) || {}; } catch { /* empty body */ }
  const secs = Number(env('SYNC_SECONDS') || env('ASPIRE_SYNC_SECONDS'));
  const deadlineMs = (Number.isFinite(secs) && secs > 0 ? secs : 120) * 1000;
  const result = await runSync({
    db: restDb(url, key),
    connectors: { aspire: aspireConnector({ deadlineMs }) },
    credentials: envCredentials(env),
    source: Number.isInteger(body.source) ? body.source : null,
    workspace: typeof body.workspace === 'string' ? body.workspace : null,
    full: body.full === true,
    trigger: body.trigger === 'cron' ? 'cron' : 'manual',
    pageSize: Number.isInteger(body.pageSize) ? body.pageSize : undefined,
  });
  const code = result.status === 'refused' ? 409 : result.status === 'error' ? 502 : 200;
  return reply({ allowed_via: gate.via, ...result }, code);
});
